package com.maizer.hanzitopinyin;

import java.io.Closeable;
import java.io.IOException;
import java.io.InputStream;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;

import com.hanzitipinyin.R;

import android.content.Context;

public class HanziToPinyin {

	private static final ArrayList<String[]> AMEND = new ArrayList<String[]>();// ◊÷∑˚∏¸’˝ ˝◊È
	private static final Comparator<Object> AMEND_BIN_COMP = new Comparator<Object>() {

		@Override
		public int compare(Object lhs, Object rhs) {
			String s1, s2;
			if (lhs instanceof String[]) {
				s1 = ((String[]) lhs)[0];
			} else {
				s1 = (String) lhs;
			}
			if (rhs instanceof String[]) {
				s2 = ((String[]) rhs)[0];
			} else {
				s2 = (String) rhs;
			}
			return s1.compareTo(s2);
		}
	};
	private static final String TAG = HanziToPinyin.class.getSimpleName();

	static {
		putAll();
	}

	public static void putAmend(String... pinyins) {
		AMEND.add(pinyins);
	}

	private static void putAll() {

		putAmend("Å@", "KAO", "QIAO", "YU");
		putAmend("ÕÚ", "WAN", "MO");
		putAmend("ÿ¢", "QI", "JI");
		putAmend("≤ª", "BU", "FOU");
		putAmend("«“", "QIE", "JU");
		putAmend("ÅO", "GUAN", "KUANG");
		putAmend("ÅU", "YI", "JI");
		putAmend("ÿ±", "TUO", "ZHE");
		putAmend("√¥", "MO", "MA", "ME", "YAO");
		putAmend("¿÷", "LE", "YUE");
		putAmend("Å\", "CHENG", "SHENG");
		putAmend("≥À", "CHENG", "SHENG");
		putAmend("Å]", "HAO", "YI");
		putAmend("ÿø", "MIE", "NIE");
		putAmend("«¨", "QIAN", "GAN");
		putAmend("Åv", "ZHI", "LUAN");
		putAmend("¡À", "LIAO", "LE");
		putAmend("–©", "XIE", "SUO");
		putAmend("ÅÖ", "QI", "ZHAI");
		putAmend("ÿΩ", "JI", "QI");
		putAmend("∫‡", "HENG", "PENG");
		putAmend("«◊", "QING");
		putAmend("Åê", "WEI", "MEN");
		putAmend(" ≤", "SHI", "SHEN");
		putAmend("¥”", "CONG", "ZONG");
		putAmend("Åó", "JIN", "SAN");
		putAmend("Åò", "BING", "EO");
		putAmend("Åö", "TUO", "CHA", "DUO");
		putAmend("Åú", "GAN", "HAN");
		putAmend("ÿÓ", "YI", "GE");
		putAmend("Åü", "CHANG", "ZHANG");
		putAmend("Å£", "CHAO", "MIAO");
		putAmend("º€", "JIA", "JIE");
		putAmend("Å¶", "YAO", "FO");
		putAmend("ºø", "JI", "QI");
		putAmend("ª·", "HUI", "KUAI");
		putAmend("¥´", "CHUAN", "ZHUAN");
		putAmend("Åº", "CHE", "JU");
		putAmend("ÿ˜", "CANG", "CHEN");
		putAmend("Å¡", "XIAN", "XUAN");
		putAmend("≤Æ", "BO", "BAI");
		putAmend("À≈", "SI", "CI");
		putAmend("À∆", "SHI", "SI");
		putAmend("Ÿ§", "QIE", "JIA", "GA");
		putAmend("ÅÃ", "YI", "CHI");
		putAmend("µË", "DIAN", "TIAN");
		putAmend("ÅŒ", "HAN", "GAN");
		putAmend("Å‘", "ZHAO", "SHAO");
		putAmend("Å◊", "ZHAN", "DIAN");
		putAmend("ÿ˝", "YI", "DIE");
		putAmend("∑", "FO", "FU", "BO", "BI");
		putAmend("ÿ˛", "GOU", "KOU");
		putAmend("Å›", "HUI", "HUAI");
		putAmend("Ÿ¶", "ER", "NAI");
		putAmend("∂±", "DONG", "TONG");
		putAmend("Ωƒ", "JIAO", "YAO");
		putAmend("ÇD", "CHENG", "TING");
		putAmend("ÇJ", "SHU", "DOU");
		putAmend("ÇM", "TUO", "TUI");
		putAmend("±„", "BIAN", "PIAN");
		putAmend("«Œ", "QIAO", "XIAO");
		putAmend("”·", "YU", "SHU");
		putAmend("Ÿπ", "SI", "QI");
		putAmend("–≈", "XIN", "SHEN");
		putAmend("Çe", "CHE", "JU");
		putAmend("Çm", "CHU", "TI");
		putAmend("Çs", "HU", "CHI");
		putAmend("Çy", "CUI", "ZU");
		putAmend("Çz", "LIANG", "LIA");
		putAmend("Çä", "LIANG", "JING");
		putAmend("Ÿ¡", "WO", "WEI");
		putAmend("Ç†", "CHENG", "CHEN");
		putAmend("Ç£", "ZHONG", "TONG");
		putAmend("Ÿ ", "JI", "JIE");
		putAmend("Ç´", "TANG", "DANG");
		putAmend("Ç∏", "CHOU", "QIAO");
		putAmend("Ç∆", "CAI", "SI");
		putAmend("Ç»", "CE", "ZE", "ZHAI");
		putAmend("ÇÃ", "ZAN", "ZA");
		putAmend("ŸÕ", "LV", "LOU");
		putAmend("ø˛", "KUI", "GUI");
		putAmend("Ç–", "ZHI", "SI");
		putAmend("Ç◊", "JIANG", "GOU");
		putAmend("Çﬂ", "QIAN", "JIAN");
		putAmend("Ç‡", "QUE", "JUE");
		putAmend("Ç·", "CANG", "CHEN");
		putAmend("ÇË", "TA", "TAN");
		putAmend("ÇÛ", "ZAO", "CAO");
		putAmend("Ç˜", "CHUAN", "ZHUAN");
		putAmend("Ç˙", "QI", "COU");
		putAmend("ÉE", "LV", "LOU");
		putAmend("ÉG", "PIAO", "BIAO");
		putAmend("É\", "CHENG", "DENG");
		putAmend("É]", "ZHAN", "ZHUAN", "CHAN");
		putAmend("Éc", "TIE", "JIAN");
		putAmend("Ée", "JIAO", "YAO");
		putAmend("Éh", "YU", "JU");
		putAmend("Éi", "E", "WU");
		putAmend("Ÿ◊", "TONG", "ZHUANG");
		putAmend("Ér", "JIA", "JIE");
		putAmend("É{", "CHAN", "TAN", "SHAN");
		putAmend("Éå", "NI", "YI");
		putAmend("É®", "RANG", "XIANG");
		putAmend("É™", "HUI", "XIE");
		putAmend("Éµ", "DUI", "RUI", "YUE");
		putAmend("øÀ", "KE", "KEI");
		putAmend("É∂", "DUI", "RUI", "YUE");
		putAmend("É∏", "CHANG", "ZHANG");
		putAmend("∂“", "DUI", "RUI", "YUE");
		putAmend("É ", "YU", "SHU");
		putAmend("¡˘", "LIU", "LU");
		putAmend("∆‰", "QI", "JI");
		putAmend("◊»", "ZI", "CI");
		putAmend("ƒ⁄", "NEI", "NA");
		putAmend("É‹", "YIN", "YOU");
		putAmend("∑Î", "FENG", "PING");
		putAmend("ÉÙ", "JING", "CHENG");
		putAmend("€…", "KAN", "QIAN");
		putAmend("∞º", "AO", "WA");
		putAmend("‘‰", "ZAO", "ZUO");
		putAmend("≈Ÿ", "PAO", "BAO");
		putAmend("…≤", "CHA", "SHA");
		putAmend("œ˜", "XUE", "XIAO");
		putAmend("Ñw", "KEI", "KE");
		putAmend("Ñx", "CHA", "SHA");
		putAmend("ÑÉ", "BAO", "BO");
		putAmend("ÿﬂ", "YAN", "SHAN");
		putAmend("ÑÜ", "DU", "ZHUO");
		putAmend("∞˛", "BO", "BAO");
		putAmend("Ñå", "ZHI", "DUAN");
		putAmend("Ñë", "DA", "ZHA");
		putAmend("Ññ", "TUAN", "ZHUAN");
		putAmend("Ñó", "LU", "JIU");
		putAmend("ΩÀ", "JIAO", "CHAO");
		putAmend("Ñ§", "JIAO", "CHAO");
		putAmend("Ñ≥", "JIN", "JING");
		putAmend("Ñµ", "XIE", "LIE");
		putAmend("æ¢", "JIN", "JING");
		putAmend("Ñ≈", "JIN", "JING");
		putAmend("≤™", "BO", "BEI");
		putAmend("¿’", "LE", "LEI");
		putAmend("Ñÿ", "WENG", "YANG");
		putAmend("Ñ‡", "JIAO", "CHAO");
		putAmend("ÑÁ", "TONG", "DONG");
		putAmend("Ñ", "RANG", "XIANG");
		putAmend("Ñ¸", "TAO", "YAO");
		putAmend("≥◊", "CHI", "SHI");
		putAmend("ÖM", "ZANG", "CANG");
		putAmend("ÿ—", "KUI", "GUI");
		putAmend("ÖT", "KUI", "GUI");
		putAmend("«¯", "QU", "OU");
		putAmend("Ö\", "KE", "QIA");
		putAmend("Ö^", "QU", "OU");
		putAmend("◊‰", "ZU", "CU");
		putAmend("µ•", "DAN", "SHAN", "CHAN");
		putAmend("ƒœ", "NAN", "NA");
		putAmend("Öi", "SHUAI", "LV");
		putAmend("≤∑", "BO", "BU");
		putAmend("Öj", "GUAN", "KUANG");
		putAmend("ø®", "KA", "QIA");
		putAmend("≥ß", "CHANG", "AN", "HAN");
		putAmend("Öz", "ZHE", "ZHAI");
		putAmend("Ö~", "ZHA", "ZHAI");
		putAmend("ÖÑ", "ZHI", "SHI");
		putAmend("œ√", "SHA", "XIA");
		putAmend("Öï", "QIAN", "LAN");
		putAmend("€Ã", "SI", "MOU");
		putAmend("Öö", "GONG", "HONG");
		putAmend("Öõ", "LIN", "MIAO");
		putAmend("Öú", "ROU", "QIU");
		putAmend("œÿ", "XIAN", "XUAN");
		putAmend("≤Œ", "CAN", "SHEN", "CEN", "SAN");
		putAmend("Ö¢", "CAN", "SHEN", "CEN", "SAN");
		putAmend("Ö£", "CAN", "SHEN", "CEN", "SAN");
		putAmend("Ö§", "CAN", "SHEN", "CEN", "SAN");
		putAmend("Ö¨", "ZHUO", "YI", "LI", "JUE");
		putAmend("Ö∞", "WEI", "YU");
		putAmend("æ‰", "JU", "GOU");
		putAmend("ﬂ∂", "TAO", "DAO");
		putAmend("’Ÿ", "ZHAO", "SHAO");
		putAmend("“∂", "YE", "XIE");
		putAmend("”ı", "XU", "YU");
		putAmend("Ö∫", "XUAN", "SONG");
		putAmend("∫œ", "HE", "GE");
		putAmend("Öº", "DOU", "CUN");
		putAmend("œ≈", "XIA", "HE");
		putAmend("ﬂ¡", "PI", "BI");
		putAmend("Ö√", "JIE", "GE");
		putAmend("∑Ò", "FOU", "PI");
		putAmend("Ö≈", "E", "HUA");
		putAmend("ø‘", "HANG", "KENG");
		putAmend("÷®", "ZHI", "ZI");
		putAmend("ﬂ≈", "YIN", "SHEN");
		putAmend("Ö»", "NA", "NE");
		putAmend("Ö…", "XUE", "CHUO", "JUE");
		putAmend("Ö ", "DOU", "RU");
		putAmend("ÖÀ", "HOU", "HONG");
		putAmend("Œ·", "WU", "YU");
		putAmend("ƒ≈", "NA", "NE");
		putAmend("Ö◊", "TUN", "TIAN");
		putAmend("ﬂ¬", "BEI", "BAI");
		putAmend("‘±", "YUAN", "YUN");
		putAmend("ﬂ√", "WAI", "HE", "WO", "WA", "GUA", "GUO");
		putAmend("Öÿ", "HUA", "QI");
		putAmend("Ö›", "WEN", "MIN");
		putAmend("ƒÿ", "NI", "NE");
		putAmend("Öﬁ", "?", "M?", "MOU");
		putAmend("Ö„", "TIE", "CHE");
		putAmend("ÖÊ", "QI", "ZHI");
		putAmend("ÖË", "ZI", "CI");
		putAmend("ﬂ…", "GUA", "GU");
		putAmend("ﬂ⁄", "ZI", "CI");
		putAmend("ÖÈ", "XU", "HOU", "GOU");
		putAmend("∫«", "HE", "A", "KE");
		putAmend("ÖÎ", "XIAO", "HAO");
		putAmend("ÖÏ", "DA", "DAN");
		putAmend("æ◊", "JU", "ZUI");
		putAmend("ÖÓ", "XIAN", "GAN");
		putAmend("’¶", "ZA", "ZE", "ZHA");
		putAmend("∫Õ", "HE", "HUO", "HU");
		putAmend("øß", "KA", "GA");
		putAmend("ÜA", "DIE", "XI");
		putAmend("ﬂ“", "JI", "XI", "QIA");
		putAmend("ø©", "KA", "LUO", "LO", "GE");
		putAmend("ÜC", "SHU", "XUN");
		putAmend("‘€", "ZAN", "ZA");
		putAmend("ø»", "KE", "HAI");
		putAmend("ÜF", "HUAI", "SHI");
		putAmend("ÜH", "E", "AN");
		putAmend("ÜJ", "WAI", "HE", "WO", "WA", "GUA", "GUO");
		putAmend("— ", "YAN", "YE");
		putAmend("ÜO", "DIE", "DI");
		putAmend("ﬂÁ", "GEN", "HEN");
		putAmend("ﬂ‹", "YUE", "HUI");
		putAmend("ﬂ‚", "JI", "JIE", "ZHAI");
		putAmend("ÜT", "YUAN", "YUN");
		putAmend("≈∂", "O", "E");
		putAmend("ƒƒ", "NA", "NEI", "NE");
		putAmend("Ü\", "PO", "BA", "BO");
		putAmend("Ü]", "LIANG", "LANG");
		putAmend("Ü`", "LIE", "LV");
		putAmend("∫ﬂ", "HENG", "HNG");
		putAmend("Üd", "CHUO", "YUE");
		putAmend("€¡", "GE", "JIA");
		putAmend("Üh", "BEI", "BAI");
		putAmend("Ük", "JIA", "QIAN");
		putAmend("Üm", "DAN", "XIAN", "YAN");
		putAmend("Üy", "GONG", "HONG");
		putAmend("ÜÅ", "WO", "WEI");
		putAmend("ÜÇ", "JIN", "YIN");
		putAmend("ª£", "HU", "XIA");
		putAmend("ÜÑ", "ER", "WA");
		putAmend("Üá", "JIE", "ZE", "JI");
		putAmend("ﬂ˙", "ZHOU", "ZHAO", "TIAO");
		putAmend("Üè", "ZHUO", "ZHAO");
		putAmend("ﬂ¯", "LAN", "LIN");
		putAmend("Üî", "ZHUN", "TUN", "XIANG", "DUI");
		putAmend("ﬂ˝", "CUI", "QI");
		putAmend("Üó", "SHA", "JIE", "DIE", "TI");
		putAmend("Üú", "YUE", "WA");
		putAmend("Üù", "ZI", "CI");
		putAmend("Üû", "BI", "TU");
		putAmend("‡®", "CHUO", "CHUAI");
		putAmend("Ü¶", "QING", "YING");
		putAmend("Ü®", "ZHE", "SHI");
		putAmend("ÜÆ", "TAN", "CHAN", "TUO");
		putAmend("‡©", "DIE", "ZHA");
		putAmend("ﬂˆ", "NUO", "RE");
		putAmend("Ü∏", "HUO", "GUO", "XU");
		putAmend("Üπ", "ZAN", "ZA");
		putAmend("‡∏", "O", "WO");
		putAmend("Üø", "HUAN", "YUAN", "XUAN", "HE");
		putAmend("∫»", "HE", "YE");
		putAmend("Ü¡", "ZHONG", "CHUANG");
		putAmend("Ü∆", "DUO", "ZHA");
		putAmend("ÜÃ", "QIAO", "JIAO");
		putAmend("ÜŒ", "DAN", "SHAN", "CHAN");
		putAmend("Üœ", "PEN", "BEN");
		putAmend("Ü–", "CAN", "SUN", "QI");
		putAmend("‘˚", "ZHA", "CHA");
		putAmend("Ü◊", "ZAO", "QIAO");
		putAmend("Ü€", "HE", "XIAO", "HU");
		putAmend("Üﬂ", "GONG", "HONG");
		putAmend("‡…", "YI", "AI");
		putAmend("‡™", "TA", "DA");
		putAmend("ÜÂ", "WA", "GU");
		putAmend("ÜÁ", "BENG", "PANG");
		putAmend("ÜÈ", "XIAN", "QIAN", "QIE");
		putAmend("‡À", "HAI", "HEI");
		putAmend("Ü˜", "ZUI", "SUI");
		putAmend("Ü¯", "ZHE", "ZHU");
		putAmend("Ü˝", "JIAO", "DAO");
		putAmend("Ü˛", "KAI", "GE");
		putAmend("áA", "SHAN", "CAN");
		putAmend("áE", "XIAO", "JIAO");
		putAmend("–Í", "XU", "SHI");
		putAmend("áN", "DE", "DEI");
		putAmend("≥∞", "CHAO", "ZHAO");
		putAmend("áb", "CHU", "XU", "SHOU");
		putAmend("ác", "TAN", "CHAN");
		putAmend("ád", "DAN", "TAN");
		putAmend("∫Ÿ", "HEI", "MO");
		putAmend("áh", "FAN", "BO");
		putAmend("ám", "CU", "ZA", "HE");
		putAmend("áp", "TUN", "KUO");
		putAmend("áu", "XU", "SHI");
		putAmend("áÄ", "ZHOU", "ZHUO");
		putAmend("áÇ", "YUE", "HUI");
		putAmend("áÑ", "JIAO", "QIAO", "CHI");
		putAmend("‡Â", "JUE", "XUE");
		putAmend("áå", "XIN", "HEN");
		putAmend("áò", "HE", "XIA");
		putAmend("áõ", "XIU", "PI");
		putAmend("áú", "ZHOU", "CHOU");
		putAmend("áù", "JI", "JIE", "ZHAI");
		putAmend("‡Í", "CA", "CHA");
		putAmend("á•", "BO", "PAO", "BAO");
		putAmend("á™", "MEI", "ME", "MO");
		putAmend("áØ", "XIE", "HAI");
		putAmend("á√", "DIAN", "DIM");
		putAmend("Ω¿", "JIAO", "JUE");
		putAmend("áÕ", "ZA", "CA");
		putAmend("á‘", "ZA", "ZAN", "CAN");
		putAmend("áŸ", "YAN", "ZA", "NIE");
		putAmend("‡Ì", "WEI", "GUO");
		putAmend("‡Ó", "JIAN", "NAN");
		putAmend("∂⁄", "DUN", "TUN");
		putAmend("áÏ", "WEI", "TONG");
		putAmend("»¶", "QUAN", "JUAN");
		putAmend("á˘", "CHUAN", "CHUI");
		putAmend("á¸", "QUAN", "JUAN");
		putAmend("‡˜", "HUAN", "YUAN");
		putAmend("€◊", "WEI", "XU");
		putAmend("àS", "YU", "ZHUN");
		putAmend("µÿ", "DI", "DE");
		putAmend("àT", "QIAN", "SU");
		putAmend("€ﬂ", "QI", "YIN");
		putAmend("àb", "MEI", "FEN");
		putAmend("àc", "RONG", "KENG");
		putAmend("àd", "TUN", "DUN");
		putAmend("àe", "BEN", "FEN");
		putAmend("àh", "DI", "LAN");
		putAmend("àm", "PAN", "BAN");
		putAmend("€Ê", "DI", "CHI");
		putAmend("€Ì", "DONG", "TONG");
		putAmend("€˘", "YUAN", "HUAN");
		putAmend("à°", "POU", "FU");
		putAmend("à©", "BENG", "FENG");
		putAmend("à™", "DI", "FANG");
		putAmend("à´", "QUE", "JUE");
		putAmend("àÆ", "XIA", "JIA");
		putAmend("¬Ò", "MAI", "MAN");
		putAmend("€Ô", "YAN", "SHAN");
		putAmend("à≤", "QIN", "JIN");
		putAmend("∆“", "PU", "BU");
		putAmend("àº", "SUI", "SU");
		putAmend("àΩ", "QING", "ZHENG");
		putAmend("à¡", "ZHENG", "CHENG");
		putAmend("à√", "CHONG", "SHANG");
		putAmend("à«", "CHU", "TOU");
		putAmend("à…", "XIAN", "KAN");
		putAmend("àÀ", "YI", "SHI");
		putAmend("‹°", "PENG", "BENG");
		putAmend("∂È", "DUO", "HUI");
		putAmend("±§", "BAO", "BU", "PU");
		putAmend("µÃ", "DI", "TI");
		putAmend("àÈ", "MAO", "MOU", "WU");
		putAmend("àÏ", "E", "AI", "YE");
		putAmend("»˚", "SAI", "SE");
		putAmend("ÃÓ", "TIAN", "ZHEN");
		putAmend("âp", "OU", "QIU");
		putAmend("ât", "ZHUAN", "TUAN");
		putAmend("ây", "ZHI", "DI");
		putAmend("â~", "ZHI", "ZHUO");
		putAmend("âë", "KUAI", "TUI");
		putAmend("âí", "TUAN", "DONG");
		putAmend("âî", "QIAO", "QUE");
		putAmend("âñ", "ZUN", "DUN");
		putAmend("âô", "DUO", "HUI");
		putAmend("â©", "YI", "TU");
		putAmend("âÆ", "XUE", "BO", "JUE");
		putAmend("â∑", "XIAN", "LAN");
		putAmend("ø«", "KE", "QIAO");
		putAmend("‚∫", "ZHI", "ZHONG");
		putAmend("â‡", "GU", "YING");
		putAmend("â·", "JIANG", "XIANG");
		putAmend("â‚", "FENG", "PANG");
		putAmend("âÈ", "XIONG", "XUAN");
		putAmend("âÌ", "YUAN", "WAN");
		putAmend("âÓ", "MAO", "WAN");
		putAmend("¥Û", "DA", "DAI", "TAI");
		putAmend("∫ª", "HANG", "BEN");
		putAmend("â˙", "TAO", "BEN");
		putAmend("â¸", "YAN", "TAO");
		putAmend("äA", "JIA", "GA");
		putAmend("äD", "DI", "TI");
		putAmend("∆Ê", "QI", "JI");
		putAmend("äI", "QUAN", "JUAN");
		putAmend("∆ı", "QI", "QIE", "XIE");
		putAmend("äL", "SHE", "CHI", "ZHA");
		putAmend("ﬁ ", "ZANG", "ZHUANG");
		putAmend("äQ", "XUN", "ZHUI");
		putAmend("äU", "PO", "HA", "TAI");
		putAmend("äW", "AO", "YU");
		putAmend("äb", "DUO", "CHE");
		putAmend("≈Æ", "NV", "RU");
		putAmend("äc", "DING", "TIAN");
		putAmend("À˝", "TA", "JIE");
		putAmend("Â˙", "FEI", "PEI");
		putAmend("äm", "FU", "YOU");
		putAmend("äo", "HAI", "JIE");
		putAmend("äs", "KENG", "HANG");
		putAmend("äv", "FOU", "PEI", "PI");
		putAmend("äx", "YUE", "JUE");
		putAmend("ä{", "NA", "NAN");
		putAmend("äÄ", "WAN", "YUAN");
		putAmend("äÖ", "NI", "NAI");
		putAmend("äà", "XIAN", "XUAN", "XU");
		putAmend("äâ", "ZHI", "YI");
		putAmend("ä£", "HUA", "HUO");
		putAmend("ÊØ", "JIAO", "XIAO");
		putAmend("ä•", "GOU", "DU");
		putAmend("¿—", "MU", "LAO");
		putAmend("äÆ", "JUN", "XUN");
		putAmend("äØ", "KUA", "HU");
		putAmend("ä¥", "E", "YA");
		putAmend("ä∑", "SHEN", "XIAN");
		putAmend("äø", "CHENG", "SHENG");
		putAmend("ä√", "WU", "MU");
		putAmend("ä≈", "CHUO", "LAI");
		putAmend("ƒ»", "NA", "NUO");
		putAmend("äÀ", "POU", "BI");
		putAmend("äÃ", "NEI", "SUI");
		putAmend("ä”", "WU", "YU");
		putAmend("ä÷", "XI", "AI");
		putAmend("ä‹", "ZHUI", "SHUI");
		putAmend("ä‚", "AI", "E");
		putAmend("äÁ", "POU", "PEI", "BU");
		putAmend("äÔ", "FU", "FAN");
		putAmend("ä˜", "QUAN", "JUAN");
		putAmend("ä˙", "QIAN", "JIN");
		putAmend("ä˛", "WAN", "WA");
		putAmend("ãB", "ZHOU", "CHOU");
		putAmend("ãC", "CHUO", "NAO");
		putAmend("ãG", "HUN", "KUN");
		putAmend("ãP", "DANG", "YANG");
		putAmend("ãS", "RUO", "CHUO");
		putAmend("ãU", "TOU", "YU");
		putAmend("ãX", "DI", "TI");
		putAmend("ã\", "RUAN", "NEN");
		putAmend("ãf", "YI", "PEI");
		putAmend("ãs", "TUO", "DUO");
		putAmend("ãÅ", "TOU", "YU");
		putAmend("ãÉ", "CHU", "ZOU");
		putAmend("ãé", "QIN", "SHEN");
		putAmend("ãë", "JIE", "SUO");
		putAmend("ã©", "HAN", "NAN");
		putAmend("ãÕ", "XIAN", "YAN", "JIN");
		putAmend("ã÷", "HUAN", "XUAN", "QIONG");
		putAmend("ã¸", "XIAN", "QIAN");
		putAmend("å@", "XIE", "HUI");
		putAmend("åA", "HUAN", "QUAN");
		putAmend("åF", "ZHU", "CHUO");
		putAmend("åI", "ZI", "MA");
		putAmend("ÀÔ", "SUN", "XUN");
		putAmend("åO", "SUN", "XUN");
		putAmend("ÂÓ", "CHAN", "CAN");
		putAmend("å_", "TU", "JIA");
		putAmend("Âµ", "MI", "FU");
		putAmend("Õ", "WAN", "YUAN");
		putAmend("åp", "BAO", "SHI");
		putAmend("º“", "JIA", "JIE");
		putAmend("Àﬁ", "SU", "XIU");
		putAmend("åÉ", "JIN", "QIN");
		putAmend("åä", "JU", "LOU");
		putAmend("åú", "LVE", "LUO");
		putAmend("å°", "KEI", "KE");
		putAmend("Œæ", "WEI", "YU");
		putAmend("å•", "SHU", "ZHU");
		putAmend("å®", "JIE", "JI");
		putAmend("å¥", "LONG", "MANG", "MENG", "PANG");
		putAmend("≥ﬂ", "CHI", "CHE");
		putAmend("Œ≤", "WEI", "YI");
		putAmend("ƒÚ", "NIAO", "SUI");
		putAmend("∆¡", "PING", "BING");
		putAmend("åŒ", "PING", "BING");
		putAmend(" Ù", "SHU", "ZHU");
		putAmend("å—", "XIE", "TI");
		putAmend("åŸ", "SHU", "ZHU");
		putAmend("Â¯", "CHE", "CAO");
		putAmend("å€", "NI", "JI");
		putAmend("å‚", "HONG", "LONG");
		putAmend("∆Ò", "QI", "KAI");
		putAmend("çQ", "KE", "BA");
		putAmend("çT", "FU", "NIE");
		putAmend("·º", "TONG", "DONG");
		putAmend("÷≈", "ZHI", "SHI");
		putAmend("·Ω", "JIAO", "QIAO");
		putAmend("çl", "XIE", "YE");
		putAmend("çå", "ZU", "CUI");
		putAmend("çö", "PI", "BI");
		putAmend("’∏", "ZHAN", "CHAN");
		putAmend("·À", "WAI", "WEI");
		putAmend("ç§", "YANG", "DANG");
		putAmend("ç™", "ZHI", "SHI");
		putAmend("ç´", "SHI", "DIE");
		putAmend("çÆ", "KAN", "ZHAN");
		putAmend("«∂", "QIAN", "KAN");
		putAmend("ç∂", "WU", "MAO");
		putAmend("ç∫", "KE", "JIE");
		putAmend("ç…", "DANG", "TANG");
		putAmend("ç ", "RONG", "YING");
		putAmend("çœ", "KAO", "QIAO");
		putAmend("ç“", "QIN", "QIAN");
		putAmend("çﬁ", "DIE", "DI");
		putAmend("ç„", "ZHAN", "CHAN");
		putAmend("ç‰", "ZHAN", "CHAN");
		putAmend("çÔ", "PI", "PEI");
		putAmend("ç˛", "JIAO", "QIAO");
		putAmend("é@", "JUE", "GUI");
		putAmend("éE", "ZHAN", "SHAN");
		putAmend("éO", "XIE", "JIE");
		putAmend("éP", "KE", "JIE");
		putAmend("éQ", "GUI", "XI", "JUAN");
		putAmend("é_", "LI", "LIE");
		putAmend("é`", "GUI", "XI", "JUAN");
		putAmend("éc", "YING", "HONG");
		putAmend("éy", "JING", "XING");
		putAmend("≤Ó", "CHA", "CHAI");
		putAmend("œÔ", "XIANG", "HANG");
		putAmend("‡˚", "TANG", "NU");
		putAmend("éí", "MO", "WA");
		putAmend("‡¸", "CHOU", "DAO");
		putAmend("é•", "JIAN", "SAN");
		putAmend("é®", "SHA", "QIE");
		putAmend("é©", "QI", "JI");
		putAmend("éª", "SHAN", "QIAO", "SHEN");
		putAmend("¥±", "CHUANG", "ZHUANG");
		putAmend("éŒ", "CHOU", "DAO");
		putAmend("π„", "GUANG", "AN");
		putAmend("é€", "MO", "MA", "ME");
		putAmend("é›", "DUN", "TUN");
		putAmend("éﬂ", "BAI", "TING");
		putAmend("µ◊", "DI", "DE");
		putAmend("∂»", "DU", "DUO");
		putAmend("éÌ", "MANG", "MENG", "PANG");
		putAmend("é", "BING", "PING");
		putAmend("éÛ", "JI", "CUO");
		putAmend("è@", "GUI", "WEI", "HUI");
		putAmend("èB", "SHA", "XIA");
		putAmend("‚€", "JIN", "QIN");
		putAmend("èZ", "QIANG", "SE");
		putAmend("èg", "PO", "PAI");
		putAmend("≈™", "NONG", "LONG");
		putAmend("è{", "JUE", "ZHANG");
		putAmend("èÉ", "JUAN", "QUAN");
		putAmend("èÖ", "XUAN", "YUAN");
		putAmend("èä", "QIANG", "JIANG");
		putAmend("µØ", "DAN", "TAN");
		putAmend("«ø", "QIANG", "JIANG");
		putAmend("èé", "DAN", "TAN");
		putAmend("èó", "DAN", "TAN");
		putAmend("èô", "QIANG", "JIANG");
		putAmend("·Í", "SHAN", "XIAN");
		putAmend("≈Ì", "PENG", "BANG");
		putAmend("è∞", "ZHUO", "BO");
		putAmend("è±", "TUO", "YI");
		putAmend("·›", "PANG", "FANG");
		putAmend("è∫", "WANG", "JIA", "WA");
		putAmend("èª", "CHENG", "ZHENG");
		putAmend("µ√", "DE", "DEI");
		putAmend("èƒ", "CONG", "ZONG");
		putAmend("è ", "SHI", "TI");
		putAmend("èÀ", "JIA", "XIA");
		putAmend("è”", "TI", "CHI");
		putAmend("è’", "ZHI", "ZHENG");
		putAmend("·Á", "ZHI", "ZHENG");
		putAmend("è◊", "ZHONG", "CHONG");
		putAmend("èŸ", "JIAO", "YAO");
		putAmend("èﬂ", "QU", "JU");
		putAmend("è‚", "DING", "TING");
		putAmend("ﬂØ", "TE", "TUI");
		putAmend("èÂ", "GAN", "HAN");
		putAmend("èÊ", "YI", "QI");
		putAmend("èÁ", "SHI", "TAI");
		putAmend("èË", "XI", "LIE");
		putAmend("èÎ", "MIN", "WEN");
		putAmend("èÏ", "MIN", "WEN");
		putAmend("‚Ï", "SONG", "ZHONG");
		putAmend("èÛ", "YU", "SHU");
		putAmend("èÙ", "QI", "SHI");
		putAmend("è˜", "TUN", "ZHUN", "DUN");
		putAmend("è¯", "QIAN", "QIN");
		putAmend("è˚", "KUANG", "WANG");
		putAmend("è˝", "KANG", "HANG");
		putAmend("‚È", "KAI", "XI");
		putAmend("êB", "MIN", "MEN");
		putAmend("‚Ù", "ZUO", "ZHA");
		putAmend("êD", "KOU", "JU");
		putAmend("êF", "NAO", "NIU");
		putAmend("êG", "TIE", "ZHAN");
		putAmend("êH", "HU", "GU");
		putAmend("êI", "CU", "JU", "ZU");
		putAmend("Àº", "SI", "SAI");
		putAmend("êJ", "YOU", "CHOU");
		putAmend("êL", "TU", "DIE");
		putAmend("êQ", "YOU", "YAO");
		putAmend("êV", "XU", "XUE");
		putAmend("êW", "BI", "PI");
		putAmend("êY", "XI", "SHU");
		putAmend("Ì•", "NEN", "NIN");
		putAmend("êf", "TIAO", "YAO");
		putAmend("êj", "XI", "QI", "XU");
		putAmend("êk", "XIAO", "JIAO");
		putAmend("êm", "HU", "KUA");
		putAmend("êw", "QUAN", "ZHUAN");
		putAmend("∂Ò", "E", "WU");
		putAmend("êÄ", "YUAN", "JUAN");
		putAmend("êÉ", "YU", "SHU");
		putAmend("êÖ", "JIE", "KE");
		putAmend("êà", "HAO", "JIAO");
		putAmend("êé", "MAN", "MEN");
		putAmend("„¶", "KUI", "LI");
		putAmend("êñ", "YI", "NIAN");
		putAmend("ê≠", "YUAN", "WAN");
		putAmend("ê∞", "LAN", "LIN");
		putAmend("ê±", "YU", "XU");
		putAmend("ê≥", "JUAN", "QUAN");
		putAmend("ê¥", "TAN", "DAN");
		putAmend("ê∑", "CHUO", "CHUI");
		putAmend("ê∏", "HUN", "MEN");
		putAmend("ê∫", "E", "WU");
		putAmend("êª", "SUO", "RUI");
		putAmend("µ¨", "DAN", "DA");
		putAmend("ê…", "TI", "SHI");
		putAmend("”‰", "YU", "TOU");
		putAmend("ê‘", "QI", "KAI");
		putAmend("ê’", "DANG", "SHANG", "TANG", "YANG");
		putAmend("ê◊", "CHEN", "XIN", "DAN");
		putAmend("êŸ", "KE", "QIA");
		putAmend("êﬂ", "CONG", "SONG");
		putAmend("ê‡", "SAI", "SI");
		putAmend("ê„", "GONG", "HONG");
		putAmend("êÂ", "SU", "SHUO");
		putAmend("ê˜", "KAI", "XI");
		putAmend("ê¯", "XI", "XIE");
		putAmend("ê˝", "CAO", "SAO");
		putAmend("ëA", "XU", "CHU");
		putAmend("„ª", "QIAN", "QIE");
		putAmend("ëE", "GONG", "HONG");
		putAmend("ëF", "CAO", "CONG");
		putAmend("ë[", "QIN", "JIN");
		putAmend("ëd", "DI", "CHI");
		putAmend("ëe", "ZHI", "ZHE");
		putAmend("ëf", "LOU", "LV");
		putAmend("ë~", "CHENG", "DENG", "ZHENG");
		putAmend("ëÑ", "DAN", "DA");
		putAmend("ëá", "DUI", "DUN", "TUN");
		putAmend("ëã", "XIAO", "JIAO");
		putAmend("ëù", "NAO", "NANG");
		putAmend("ë¢", "JIAO", "JI");
		putAmend("ë§", "XUAN", "HUAN");
		putAmend("ë®", "CAO", "SAO");
		putAmend("ëπ", "AI", "YI", "NI");
		putAmend("ëº", "QI", "JI");
		putAmend("ëæ", "LAN", "XIAN");
		putAmend("ë€", "MI", "MO");
		putAmend("ëﬁ", "GANG", "ZHUANG");
		putAmend("Ì∞", "GANG", "ZHUANG");
		putAmend("ëﬂ", "GANG", "ZHUANG");
		putAmend("œ∑", "XI", "HU");
		putAmend("ëÔ", "XI", "HU");
		putAmend("ëÒ", "XI", "HU");
		putAmend("ëÚ", "XI", "HU");
		putAmend("±‚", "BIAN", "PIAN");
		putAmend("ë˚", "SHANG", "JIONG");
		putAmend("‘˙", "ZA", "ZHA");
		putAmend("íA", "LE", "LI", "CAI");
		putAmend("∆À", "PU", "PO", "PIAO");
		putAmend("∞«", "BA", "PA");
		putAmend("íB", "FAN", "FU");
		putAmend("íF", "DIAO", "DI", "YUE", "LI");
		putAmend("ø∏", "KANG", "GANG");
		putAmend("íG", "YU", "WU");
		putAmend("íH", "YU", "WU", "KU");
		putAmend("íL", "TUO", "CHI", "YI");
		putAmend("íM", "GU", "XI", "GE", "JIE");
		putAmend("íQ", "XI", "CHA", "QI");
		putAmend("íR", "QIAN", "QIN");
		putAmend("íU", "BA", "AO");
		putAmend("íV", "XI", "ZHE");
		putAmend("íX", "ZHI", "SUN", "KAN");
		putAmend("í[", "KUANG", "WANG", "ZAI");
		putAmend("í_", "HU", "GU");
		putAmend("íb", "DAN", "SHEN");
		putAmend("íf", "NE", "NI", "RUI", "NA");
		putAmend("’€", "ZHE", "SHE");
		putAmend("íh", "POU", "FU");
		putAmend("íj", "AO", "NIU");
		putAmend("«¿", "QIANG", "CHENG");
		putAmend("ín", "ZHI", "ZHAI");
		putAmend("íp", "BU", "PU");
		putAmend("íq", "YAO", "TAO");
		putAmend("íu", "HE", "QIA");
		putAmend("íy", "PI", "PEI");
		putAmend("ƒ®", "MO", "MA");
		putAmend("í~", "JIA", "YA");
		putAmend("∑˜", "FU", "BI");
		putAmend("≤", "CHAI", "CA");
		putAmend("∞Ë", "BAN", "PAN");
		putAmend("Õÿ", "TUO", "TA", "ZHI");
		putAmend("ﬁ÷", "AO", "NIU");
		putAmend("æ–", "JU", "GOU");
		putAmend("ﬁ’", "PAN", "PIN", "FAN");
		putAmend("‘Ò", "ZE", "ZHAI");
		putAmend("¿®", "KUO", "GUA");
		putAmend("ﬁ◊", "JIE", "JIA");
		putAmend("íé", "CUN", "ZUN");
		putAmend("ﬁŸ", "ZA", "ZAN");
		putAmend("íè", "YI", "CHI", "HAI");
		putAmend("íë", "CE", "SE", "CHUO");
		putAmend("◊ß", "ZHUAI", "YE");
		putAmend(" ∞", "SHI", "SHE");
		putAmend("íï", "KUO", "GUANG");
		putAmend("øÊ", "KUA", "KU");
		putAmend("íù", "RU", "NA");
		putAmend("í°", "DIE", "SHE");
		putAmend("ŒŒ", "ZHUA", "WO");
		putAmend("–Æ", "XIE", "JIA");
		putAmend("í®", "TUO", "SHUI");
		putAmend("í≠", "SUO", "SHA");
		putAmend("Í˝", "SUO", "SHA");
		putAmend("íÆ", "KENG", "QIAN");
		putAmend("í≤", "BANG", "PENG");
		putAmend("í∂", "XIE", "JIA");
		putAmend("íπ", "JIAO", "KU");
		putAmend("íª", "HUO", "CHI");
		putAmend("íº", "TU", "SHU", "CHA");
		putAmend("íΩ", "POU", "FU");
		putAmend("ﬁ€", "LUO", "LV");
		putAmend("íø", "SHU", "SONG", "SOU");
		putAmend("í¿", "YE", "YU");
		putAmend("í¡", "JUE", "ZHUO");
		putAmend("í√", "BU", "PU", "ZHI");
		putAmend("í…", "TUO", "SHUI");
		putAmend("íÃ", "WAN", "YU");
		putAmend("í—", "FU", "BU");
		putAmend("í”", "WO", "LUO");
		putAmend("í‘", "JUAN", "QUAN");
		putAmend("ƒÌ", "NIAN", "NIE");
		putAmend("í⁄", "RUO", "WEI", "RE");
		putAmend("í‹", "WO", "XIA");
		putAmend("í·", "QING", "QIAN");
		putAmend("íÁ", "QIAN", "WAN");
		putAmend("íÌ", "NI", "NIE", "YI");
		putAmend("íÓ", "HUO", "XU");
		putAmend("íÔ", "SHAN", "YAN");
		putAmend("í", "ZHENG", "DING");
		putAmend("íÙ", "ZOU", "ZHOU", "CHOU");
		putAmend("µß", "DAN", "SHAN");
		putAmend("≤Ù", "CHAN", "XIAN", "CAN", "SHAN");
		putAmend("ì@", "ZHENG", "KENG");
		putAmend("ìA", "JIU", "YOU");
		putAmend("ìF", "PI", "CHE");
		putAmend("Ã·", "TI", "DI");
		putAmend("ìK", "ZONG", "SONG");
		putAmend("ìN", "HUANG", "YONG");
		putAmend("ìS", "ZAN", "ZUAN");
		putAmend("ìT", "XU", "JU");
		putAmend("ìU", "KE", "QIA");
		putAmend("¥ß", "CHUAI", "TUAN", "ZHUI");
		putAmend("ìW", "TI", "DI");
		putAmend("Ω“", "JIE", "QI");
		putAmend("ì_", "CHONG", "DONG");
		putAmend("ﬁÈ", "SHE", "DIE", "YE");
		putAmend("ìb", "QIAN", "JIAN");
		putAmend("ìo", "CHOU", "ZOU");
		putAmend("ìr", "RONG", "NANG");
		putAmend("ìs", "BANG", "PENG");
		putAmend("ìx", "NU", "NUO", "NOU");
		putAmend("ìy", "LA", "XIE", "XIAN");
		putAmend("ìÉ", "JIE", "ZHE");
		putAmend("ìÑ", "PAN", "BAN", "PO");
		putAmend("ìà", "ZHI", "NAI");
		putAmend("ìå", "QIANG", "CHENG");
		putAmend("ìç", "TIAN", "SHEN");
		putAmend("ìê", "NA", "NUO");
		putAmend("…„", "SHE", "NIE");
		putAmend("ìó", "SA", "SHA", "SHAI");
		putAmend("ìò", "CHAN", "SUN");
		putAmend("ìö", "JIU", "LIU", "LIAO", "JIAO", "NAO");
		putAmend("ìû", "FENG", "PENG");
		putAmend("ìü", "DI", "TU", "ZHI");
		putAmend("ì†", "QI", "JI", "CHA");
		putAmend("ì°", "SOU", "SONG");
		putAmend("ì©", "GAI", "XI");
		putAmend("ì™", "HU", "CHU");
		putAmend("ìØ", "ZHI", "NAI");
		putAmend("ƒ¶", "MO", "MA");
		putAmend("ì∞", "JIANG", "QIANG");
		putAmend("ì≥", "AO", "QIAO");
		putAmend("ìµ", "NIE", "CHE");
		putAmend("ì∑", "CHAN", "CAN");
		putAmend("ì∫", "SE", "MI", "SU");
		putAmend("ìº", "JIAO", "CHAO");
		putAmend("ìΩ", "CHAN", "XIAN", "CAN", "SHAN");
		putAmend("ìæ", "KENG", "QIAN");
		putAmend("ìÀ", "ZAN", "ZEN", "QIAN");
		putAmend("ì—", "HENG", "GUANG");
		putAmend("ì’", "ZHENG", "CHENG");
		putAmend("ì÷", "HUI", "WEI");
		putAmend("ì€", "DAN", "SHAN");
		putAmend("ìﬂ", "XIAO", "SOU");
		putAmend("¥È", "CUO", "ZUO");
		putAmend("ì„", "WEI", "TUO");
		putAmend("ìÍ", "QIAO", "YAO", "JI");
		putAmend("ìÎ", "ZHUA", "WO");
		putAmend("ìÒ", "ZE", "ZHAI");
		putAmend("ì˜", "QING", "JING");
		putAmend("ì¸", "QIA", "JIA", "YE");
		putAmend("ﬂ®", "PI", "BO");
		putAmend("Î¢", "BO", "BAI");
		putAmend("îT", "ZHI", "JIE");
		putAmend("îY", "LIE", "LA");
		putAmend("î^", "LI", "LUO", "YUE");
		putAmend("î`", "TI", "ZHI", "ZHAI");
		putAmend("îc", "CA", "SA");
		putAmend("îh", "JUN", "PEI");
		putAmend("îi", "LI", "LUO");
		putAmend("îj", "LA", "LAI");
		putAmend("îm", "LU", "LUO");
		putAmend("‘‹", "ZAN", "CUAN");
		putAmend("îs", "XIAN", "JIAN");
		putAmend("îz", "SHE", "NIE");
		putAmend("î}", "MI", "MO");
		putAmend("îÄ", "ZAN", "CUAN");
		putAmend("îÉ", "LI", "SHAI");
		putAmend("îâ", "LI", "LUO");
		putAmend("îå", "QI", "YI", "JI");
		putAmend("îê", "GAN", "HAN");
		putAmend("îñ", "WU", "MOU");
		putAmend("îô", "CHU", "SHOU");
		putAmend("îö", "GE", "GUO");
		putAmend("îü", "DUO", "DUI");
		putAmend("î£", "DUO", "DUI");
		putAmend("î¶", "DUO", "QUE");
		putAmend("∂ÿ", "DUN", "DUI");
		putAmend("î™", "QI", "YI", "JI");
		putAmend("î¨", "XIAO", "XUE");
		putAmend("î≠", "DUO", "QUE");
		putAmend(" ˝", "SHU", "SHUO");
		putAmend("î±", "AI", "ZHU");
		putAmend("îµ", "SHU", "SHUO");
		putAmend("î∏", "XIONG", "XUAN");
		putAmend("îΩ", "ZHUO", "ZHU");
		putAmend("îæ", "YI", "DU");
		putAmend("î¡", "LI", "TAI");
		putAmend("î«", "JUE", "JIAO");
		putAmend("îÀ", "YU", "ZHONG");
		putAmend("îÕ", "WEI", "MEN");
		putAmend("Œ”", "WO", "GUAN");
		putAmend("î”", "TOU", "TIAO");
		putAmend("î’", "YIN", "ZHI");
		putAmend("î‚", "CHAN", "JIE");
		putAmend("Ï∂", "YU", "WU");
		putAmend("îÂ", "LIU", "YOU");
		putAmend("≈‘", "PANG", "BANG");
		putAmend("îË", "PI", "BI");
		putAmend("Í∫", "GAN", "HAN");
		putAmend("ï@", "TAI", "YING");
		putAmend("ïA", "DI", "DE");
		putAmend("ïH", "TUN", "ZHUN");
		putAmend("ïi", "DIE", "YI");
		putAmend("ïv", "XU", "KUA");
		putAmend("Í…", "SHENG", "CHENG");
		putAmend("æ∞", "JING", "YING");
		putAmend("ïí", "QI", "DU");
		putAmend("ïï", "AN", "YAN");
		putAmend("ï§", "SHU", "DU");
		putAmend("ï©", "JIAN", "LAN");
		putAmend("±©", "BAO", "PU");
		putAmend("∆ÿ", "PU", "BAO");
		putAmend("ï˚", "ZENG", "CENG");
		putAmend("‘¯", "ZENG", "CENG");
		putAmend("ï¸", "CAN", "QIAN", "JIAN");
		putAmend("ï˛", "HUI", "KUAI");
		putAmend("ñA", "QIE", "HE");
		putAmend("ñC", "BI", "PI");
		putAmend("ñD", "FEN", "BAN");
		putAmend("ñF", "FEI", "KU");
		putAmend("Î‘", "QU", "XU", "CHUN");
		putAmend("ñH", "NV", "GA");
		putAmend("ñK", "JUAN", "ZUI");
		putAmend("ñM", "HUANG", "MANG", "WANG");
		putAmend("≥Ø", "ZHAO", "CHAO");
		putAmend("∆⁄", "QI", "JI");
		putAmend("ñS", "TONG", "CHUANG");
		putAmend("ñX", "SHU", "ZHU");
		putAmend(" ı", "SHU", "ZHU");
		putAmend("÷Ï", "ZHU", "SHU");
		putAmend("∆”", "PU", "PO", "PIAO");
		putAmend("ñ]", "DAO", "TIAO", "MU");
		putAmend("ñ_", "QIU", "GUI");
		putAmend("ñf", "YU", "WU");
		putAmend("…º", "SHAN", "SHA");
		putAmend("ñk", "REN", "ER");
		putAmend("Ëº", "SHAO", "BIAO");
		putAmend("ñl", "TUO", "ZHE");
		putAmend("ñm", "DI", "DUO");
		putAmend("ñq", "GU", "GAI");
		putAmend("ñs", "YI", "LI", "DUO", "TUO");
		putAmend("ñy", "SI", "ZHI", "XI");
		putAmend("ñz", "YUAN", "WAN");
		putAmend("ñ{", "FEI", "BEI");
		putAmend("ñÄ", "SHU", "DUI");
		putAmend("ñÉ", "NIU", "CHOU");
		putAmend("ñÜ", "WO", "YUE");
		putAmend("ñä", "PI", "MI");
		putAmend("Ë ", "FANG", "BING");
		putAmend("ñê", "HU", "DI");
		putAmend("÷¶", "ZHI", "QI");
		putAmend("Ë»", "CONG", "ZONG");
		putAmend("ñö", "DI", "DUO");
		putAmend("ñû", "XIAN", "ZHEN");
		putAmend("ñü", "SI", "TAI");
		putAmend("Ë€", "JU", "GOU");
		putAmend("ñ¢", "BAO", "FU");
		putAmend("ñ§", "YI", "XIE");
		putAmend("Ëﬁ", "TUO", "DUO");
		putAmend("ñ™", "YI", "DUO", "LI");
		putAmend("ñ´", "NI", "CHI");
		putAmend("ñÆ", "PAN", "BAN");
		putAmend("ñ≥", "YANG", "YING");
		putAmend("∞ÿ", "BAI", "BO");
		putAmend("πÒ", "GUI", "JU");
		putAmend("◊ı", "ZUO", "ZHA");
		putAmend("ñª", "ZHI", "DIE");
		putAmend("ñº", "ZHA", "ZU");
		putAmend("≤È", "CHA", "ZHA");
		putAmend("ñø", "BU", "PU");
		putAmend("ñ¬", "BA", "FU", "PEI", "BO", "BIE");
		putAmend("ñ√", "DUO", "ZUO", "WU");
		putAmend("ñƒ", "BI", "BIE");
		putAmend("ñ»", "BEI", "PEI");
		putAmend("ñ…", "SHI", "FEI");
		putAmend("ñÀ", "CHA", "ZHA");
		putAmend("’§", "ZHA", "SHAN", "SHI", "CE");
		putAmend("Ë›", "LI", "YUE");
		putAmend("ñ÷", "QI", "QIE");
		putAmend("∆‹", "QI", "XI");
		putAmend("ËÈ", "GUA", "TIAN");
		putAmend("ñﬁ", "BEN", "BING");
		putAmend("–£", "XIAO", "JIAO");
		putAmend("ñÂ", "YI", "XIE");
		putAmend("ñÁ", "JIAN", "ZUN");
		putAmend("ñÎ", "YOU", "YU");
		putAmend("∫À", "HE", "HU");
		putAmend("ñÒ", "ZHI", "YI");
		putAmend("ËÏ", "HENG", "HANG");
		putAmend("ñı", "YI", "TI");
		putAmend("Ω€", "JIE", "JU");
		putAmend("ñ¸", "YU", "MOU");
		putAmend("ñ˝", "ZA", "ZAN");
		putAmend("Ë„", "RAO", "NAO");
		putAmend("ËÌ", "GUI", "HUI");
		putAmend("óF", "CHEN", "ZHEN");
		putAmend("óH", "TING", "YING");
		putAmend("óL", "BEN", "FAN");
		putAmend("óV", "SU", "YIN");
		putAmend("ó]", "XUAN", "JUAN", "XIE");
		putAmend("ó^", "TU", "CHA");
		putAmend("ó`", "AO", "YOU");
		putAmend("óe", "REN", "ER");
		putAmend("…“", "SHAO", "SAO");
		putAmend("ót", "SI", "QI");
		putAmend("ó{", "CHAN", "YAN");
		putAmend("óÄ", "BIN", "BING");
		putAmend("óÉ", "CHOU", "TAO", "DAO");
		putAmend("óå", "CONG", "SONG");
		putAmend("π˜", "GUN", "HUN");
		putAmend("óë", "DE", "ZHE");
		putAmend("óì", "PAI", "BEI", "PEI");
		putAmend("óî", "BANG", "POU", "BEI");
		putAmend("óò", "LI", "LIE");
		putAmend("È¶", "DI", "DAI", "TI");
		putAmend("ó®", "QUAN", "JUAN");
		putAmend("ó™", "REN", "SHEN");
		putAmend("¿‚", "LENG", "LING");
		putAmend("ó≠", "FU", "SU");
		putAmend("óØ", "ZOU", "SOU");
		putAmend("Ë˛", "ZHAO", "ZHUO");
		putAmend("ó∏", "JIE", "QIE");
		putAmend("óπ", "CHOU", "ZHOU", "DIAO");
		putAmend("óº", "CHENG", "SHENG");
		putAmend("óΩ", "ZU", "CUI");
		putAmend("óæ", "QIANG", "KONG");
		putAmend("◊µ", "ZHUI", "CHUI");
		putAmend("ó—", "QUAN", "JUAN");
		putAmend("óŸ", "DUO", "CHUAN");
		putAmend("ó€", "WEI", "HUI");
		putAmend("óﬂ", "JIAN", "HAN");
		putAmend("È©", "ZHEN", "SHEN");
		putAmend("ó‚", "YAN", "YA");
		putAmend("È´", "ZHA", "CHA");
		putAmend("óÎ", "GUO", "KUA");
		putAmend("ó˘", "JI", "ZHI");
		putAmend("ó¸", "KU", "HU");
		putAmend("òB", "SONG", "CONG");
		putAmend("òC", "XUAN", "YUAN");
		putAmend("òD", "YANG", "YING");
		putAmend("òG", "DIE", "YE");
		putAmend("òJ", "SHUN", "DUN");
		putAmend("È®", "COU", "ZOU");
		putAmend("òN", "DI", "SHI");
		putAmend("ø¨", "KAI", "JIE");
		putAmend("òS", "LE", "YUE");
		putAmend("òX", "WEN", "YUN");
		putAmend("ò[", "BI", "PI");
		putAmend("ò^", "ZHAN", "NIAN", "ZHEN");
		putAmend("ò_", "FU", "BO");
		putAmend("òc", "JIAN", "JIN");
		putAmend("òf", "SHA", "XIE");
		putAmend("òç", "QIAN", "LIAN", "XIAN");
		putAmend("òï", "DIAN", "ZHEN");
		putAmend("º˜", "JIAN", "KAN");
		putAmend("Èƒ", "BIN", "BING");
		putAmend("òõ", "XI", "DIE");
		putAmend("òú", "JI", "GUI");
		putAmend("òü", "RONG", "YONG");
		putAmend("ò§", "TUAN", "SHUAN", "QUAN");
		putAmend("È ", "QI", "SE");
		putAmend("òß", "CUI", "ZHI");
		putAmend("ò©", "YOU", "CHAO");
		putAmend("ò¥", "MAN", "WAN");
		putAmend("ò∑", "LE", "YUE", "YAO", "LAO");
		putAmend("ò∫", "CONG", "ZONG");
		putAmend("òª", "LI", "CHI");
		putAmend("ò»", "CHAO", "JIAO");
		putAmend("òÕ", "JIU", "LIAO");
		putAmend("ƒ£", "MO", "MU");
		putAmend("ò“", "NIAO", "MU");
		putAmend("ò◊", "SHA", "XIE");
		putAmend("òÏ", "FA", "FEI");
		putAmend("òÔ", "RAO", "NAO");
		putAmend("òˆ", "ZHAN", "JIAN");
		putAmend("ò˙", "TUI", "DUN");
		putAmend("ò¸", "TANG", "CHENG");
		putAmend("ò˛", "SU", "QIU");
		putAmend("ôA", "TAN", "DIAN");
		putAmend("ôH", "TONG", "CHUANG");
		putAmend("ôI", "ZENG", "CENG");
		putAmend("ôJ", "FEN", "FEI");
		putAmend("ôL", "RAN", "YAN");
		putAmend("ô[", "CU", "CHU");
		putAmend("ô]", "SHU", "QIAO");
		putAmend("ôq", "PING", "BO");
		putAmend("ôu", "GUI", "HUI");
		putAmend("ôy", "ZHAI", "SHI", "TU");
		putAmend("ôÑ", "CHOU", "TAO", "DAO");
		putAmend("ôâ", "BIN", "BING");
		putAmend("ôå", "QIAN", "LIAN");
		putAmend("ôç", "NI", "MI");
		putAmend("ôë", "JIAN", "KAN");
		putAmend("ôì", "NOU", "RUAN", "RU");
		putAmend("ô§", "HUANG", "GUO", "GU");
		putAmend("ô¨", "LV", "CHU");
		putAmend("ô≠", "MIE", "MEI");
		putAmend("ôµ", "LI", "YUE");
		putAmend("ô∑", "ZHUO", "ZHU");
		putAmend("ô√", "JUE", "JI");
		putAmend("ô∆", "HUAI", "GUI");
		putAmend("ô ", "LA", "LAI");
		putAmend("ôŸ", "CHAN", "ZHAN");
		putAmend("ôﬁ", "WEI", "ZUI");
		putAmend("ôˆ", "YU", "YI");
		putAmend("ô˜", "QIAN", "XIAN");
		putAmend("ô˙", "CHU", "QU", "XI");
		putAmend("ô˝", "YI", "YIN");
		putAmend("ö@", "XI", "KAI");
		putAmend("öF", "SHUO", "SOU");
		putAmend("öG", "EI", "AI");
		putAmend("öH", "XU", "CHUA");
		putAmend("öI", "CHI", "CHUAI");
		putAmend("öK", "KAN", "QIAN");
		putAmend("öM", "KAN", "KE");
		putAmend("öP", "YAN", "YIN");
		putAmend("öV", "JIN", "QUN");
		putAmend("Ï®", "XI", "SHE");
		putAmend("öa", "LIAN", "HAN");
		putAmend("öl", "ZHI", "CHI");
		putAmend("öo", "SE", "SHA");
		putAmend("öz", "MO", "WEN");
		putAmend("öÑ", "QING", "JING");
		putAmend("öÜ", "FOU", "BO");
		putAmend("÷≥", "ZHI", "SHI");
		putAmend("öá", "YE", "YAN");
		putAmend("öâ", "HUN", "MEI");
		putAmend("öï", "KUI", "HUI");
		putAmend("“Û", "YIN", "YAN");
		putAmend("ö†", "QING", "KENG", "SHENG");
		putAmend("ö£", "KE", "QIAO");
		putAmend("ö§", "KE", "QIAO");
		putAmend("ö•", "XIAO", "YAO");
		putAmend("öØ", "GUAN", "WAN");
		putAmend("∂æ", "DU", "DAI");
		putAmend("ö√", "DOU", "NUO");
		putAmend("öÀ", "SAI", "SUI");
		putAmend(" œ", "SHI", "ZHI");
		putAmend("√•", "MENG", "MANG");
		putAmend("öﬁ", "YANG", "RI");
		putAmend("öÈ", "ZHENG", "CHENG");
		putAmend("ö", "GUI", "JIU");
		putAmend("öÒ", "BIN", "PA");
		putAmend("öı", "ZHUO", "QUE");
		putAmend("Ã¿", "TANG", "SHANG");
		putAmend("õD", "ZHI", "JI");
		putAmend("„È", "GU", "YU");
		putAmend("õN", "GAN", "HAN", "CEN");
		putAmend("„Î", "WEN", "MEN");
		putAmend("õP", "FANG", "PANG");
		putAmend("õR", "HU", "HUANG");
		putAmend("õS", "NIU", "YOU");
		putAmend("…Ú", "SHEN", "CHEN");
		putAmend("õ\", "NV", "NIU");
		putAmend("õ]", "MEI", "MO");
		putAmend("Ì≥", "TA", "DA");
		putAmend("õ^", "MI", "WU");
		putAmend("õ`", "HONG", "PANG");
		putAmend("õd", "ZHUI", "ZI");
		putAmend("√ª", "MEI", "MO");
		putAmend("õk", "TUO", "DUO");
		putAmend("„ı", "TUO", "DUO");
		putAmend("õm", "MI", "LI");
		putAmend("õn", "YI", "CHI");
		putAmend("–π", "XIE", "YI");
		putAmend("õu", "YI", "DIE");
		putAmend("≤¥", "BO", "PO");
		putAmend("√⁄", "MI", "BI");
		putAmend("õ{", "CHU", "SHE");
		putAmend("õ|", "YOU", "AO");
		putAmend("õÄ", "PENG", "PING");
		putAmend("õá", "YUE", "SA");
		putAmend("õâ", "JUE", "XUE");
		putAmend("„Ò", "LONG", "SHUANG");
		putAmend("„¯", "LUO", "PO");
		putAmend("‘Û", "ZE", "SHI");
		putAmend("»˜", "SA", "XI");
		putAmend("õõ", "SE", "QI", "ZI");
		putAmend("œ¥", "XI", "XIAN");
		putAmend("õ°", "AN", "YAN", "E");
		putAmend("õ´", "SU", "SHUO");
		putAmend("õ≠", "QIE", "JIE");
		putAmend("«≥", "QIAN", "JIAN");
		putAmend("‰´", "KUAI", "HUI");
		putAmend("‰∞", "HU", "XU");
		putAmend("ø£", "JUN", "XUN");
		putAmend("õ¡", "YOU", "DI");
		putAmend("õ∆", "YING", "CHENG");
		putAmend("õÕ", "FENG", "HONG");
		putAmend("õ‘", "SUI", "NEI");
		putAmend("”ø", "YONG", "CHONG");
		putAmend("õ‚", "TUN", "YUN");
		putAmend("Œ–", "WO", "GUO");
		putAmend("õÏ", "SHOU", "TAO");
		putAmend("õÔ", "KONG", "NANG");
		putAmend("õ", "WAN", "WO", "YUAN");
		putAmend("õ˘", "QIE", "JI");
		putAmend("õ˝", "GUO", "GUAN");
		putAmend("Ã ", "TANG", "CHANG");
		putAmend("ƒ◊", "NAO", "CHUO", "ZHUO");
		putAmend("úK", "PING", "PENG");
		putAmend("‰ƒ", "PI", "PEI");
		putAmend("úM", "YU", "XU");
		putAmend("úQ", "JING", "CHENG");
		putAmend("úV", "NIAN", "SHEN");
		putAmend("úW", "BIAO", "HU");
		putAmend("¥æ", "CHUN", "ZHUN");
		putAmend("úb", "WEN", "MIN");
		putAmend("úc", "RUO", "RE", "LUO");
		putAmend("‰¬", "DU", "DOU");
		putAmend("‰≈", "MIAN", "SHENG");
		putAmend("úr", "QIU", "WU");
		putAmend("«˛", "QU", "JU");
		putAmend("úu", "WO", "GUO");
		putAmend("úv", "TI", "DI");
		putAmend("∏€", "GANG", "JIANG");
		putAmend("úÇ", "HONG", "QING");
		putAmend("úì", "HUI", "MIN", "XU");
		putAmend("ú°", "MIN", "HUN");
		putAmend("ú®", "TUAN", "NUAN");
		putAmend("‰–", "QIU", "JIAO");
		putAmend("ú©", "QIU", "JIAO");
		putAmend("‰Œ", "YAN", "YIN");
		putAmend("ú´", "TANG", "SHANG");
		putAmend("ú∞", "BAN", "PAN");
		putAmend("ú≥", "ZHUANG", "HUN");
		putAmend("¿£", "KUI", "HUI");
		putAmend("úΩ", "FENG", "HONG");
		putAmend("úƒ", "YAN", "GUI");
		putAmend("ú«", "LIAN", "NIAN", "XIAN");
		putAmend("úÕ", "DA", "TA");
		putAmend("‰⁄", "ZHEN", "QIN");
		putAmend("ƒÁ", "NI", "NIAO");
		putAmend("ú‰", "CHU", "XU");
		putAmend("úÈ", "HAO", "XUE");
		putAmend("úÎ", "QI", "XI", "XIE");
		putAmend("úÓ", "XING", "YING");
		putAmend("úı", "ZE", "HAO");
		putAmend("ùG", "HU", "XU");
		putAmend("ùY", "CONG", "SONG");
		putAmend("ù`", "TUAN", "ZHUAN");
		putAmend("ùm", "FENG", "PENG");
		putAmend("‰", "LUO", "TA");
		putAmend("ùp", "BEN", "PENG");
		putAmend("ùr", "CHONG", "ZHUANG");
		putAmend("ùt", "HUO", "KUO");
		putAmend("ùx", "LIAO", "LIU");
		putAmend("ù|", "CONG", "ZONG");
		putAmend("ùÉ", "CONG", "ZONG");
		putAmend("ùá", "PI", "PIE");
		putAmend("ùâ", "JIAO", "QIAO");
		putAmend("ùã", "DANG", "XIANG");
		putAmend("ùî", "XI", "YA");
		putAmend("‰Í", "HUANG", "GUANG");
		putAmend("¡ ", "LAO", "LIAO");
		putAmend("ùú", "CONG", "ZONG");
		putAmend("ù†", "TAN", "SHAN");
		putAmend("ù¢", "KUI", "HUI");
		putAmend("ù§", "TU", "ZHA");
		putAmend("ù•", "SAN", "SA");
		putAmend("≥Œ", "CHENG", "DENG");
		putAmend("‰¯", "SHU", "ZHU");
		putAmend("ùπ", "HONG", "GONG");
		putAmend("ù∆", "MIAN", "SHENG");
		putAmend("ù…", "ZE", "SHI");
		putAmend("ùœ", "WAN", "MAN");
		putAmend("ù“", "KUAI", "HUI");
		putAmend("Â£", "DAN", "TAN");
		putAmend("ù„", "GUO", "WO");
		putAmend("ùÂ", "FEN", "PEN");
		putAmend("ùÁ", "JI", "SHA");
		putAmend("ùË", "HUI", "HUO");
		putAmend("ùÏ", "DING", "TING");
		putAmend("ù", "MI", "NI");
		putAmend("Â®", "BI", "PI");
		putAmend("ù˚", "CUI", "ZUI");
		putAmend("ûC", "HUO", "HU");
		putAmend("ûF", "JUN", "XUN");
		putAmend("ûG", "AI", "KAI", "KE");
		putAmend("Â™", "ZHUO", "ZHAO");
		putAmend("ûS", "WEI", "DUI");
		putAmend("ûT", "LUO", "PO");
		putAmend("ûU", "ZAN", "CUAN");
		putAmend("û^", "DU", "DOU");
		putAmend("ûf", "MIE", "MO");
		putAmend("∆Ÿ", "PU", "BAO");
		putAmend("ûj", "CHENG", "DENG");
		putAmend("ûw", "WEI", "DUI");
		putAmend("ûx", "HUAI", "WAI");
		putAmend("û{", "LONG", "SHUANG");
		putAmend("ûà", "JIAN", "ZUN");
		putAmend("ûè", "RANG", "NANG");
		putAmend("ûï", "ZHUO", "JIAO", "ZE");
		putAmend("û£", "ZAN", "CUAN");
		putAmend("û™", "DANG", "TANG");
		putAmend("ûµ", "XUN", "QUAN");
		putAmend("Ï·", "HUO", "BIAO");
		putAmend("û¡", "ZHA", "YU");
		putAmend("û«", "FEN", "BEN");
		putAmend("Í¡", "JIONG", "GUI");
		putAmend("û–", "PANG", "FENG");
		putAmend("û„", "ZHUO", "CHU");
		putAmend("≈⁄", "PAO", "BAO");
		putAmend("û‰", "PAO", "FOU");
		putAmend("ûË", "SHAN", "QIAN");
		putAmend("ûÏ", "JIAO", "YAO");
		putAmend("û˙", "TONG", "DONG");
		putAmend("¿”", "LAO", "LUO");
		putAmend("üJ", "FU", "PAO");
		putAmend("üL", "XIE", "CHE");
		putAmend("ü[", "XUN", "HUN");
		putAmend("ü]", "JUAN", "YE");
		putAmend("üa", "QU", "JUN");
		putAmend("üc", "XIE", "CHE");
		putAmend("üd", "JI", "QI");
		putAmend("üq", "CHAO", "JU");
		putAmend("üs", "WO", "AI");
		putAmend("üt", "ZONG", "CONG");
		putAmend("üy", "XI", "YI");
		putAmend("ÏÃ", "ZHUO", "CHAO");
		putAmend("üÇ", "XIONG", "YING");
		putAmend("üá", "XIONG", "YING");
		putAmend("üê", "HUI", "YUN", "XUN");
		putAmend("üö", "SHAN", "QIAN");
		putAmend("üõ", "XI", "YI");
		putAmend("ü§", "YE", "ZHA");
		putAmend("ü∏", "EN", "YUN");
		putAmend("ü¿", "HE", "XIAO");
		putAmend("ü–", "CONG", "ZONG");
		putAmend("ü—", "LU", "AO");
		putAmend("ü‘", "PENG", "FENG");
		putAmend("ü’", "SUI", "CUI");
		putAmend("ÏŸ", "YUN", "YU");
		putAmend("üﬂ", "HAN", "RAN");
		putAmend("üÌ", "CHAN", "DAN");
		putAmend("ü˜", "JIAO", "QIAO", "JUE", "ZHUO");
		putAmend("ü¸", "TONG", "DONG");
		putAmend("†M", "TAI", "LIE");
		putAmend("†h", "RONG", "YING");
		putAmend("†i", "LI", "LIE");
		putAmend("†m", "LA", "LIE");
		putAmend("†p", "KUANG", "HUANG");
		putAmend("†w", "YAN", "XUN");
		putAmend("◊¶", "ZHAO", "ZHUA");
		putAmend("†ç", "ZHAO", "ZHUA");
		putAmend("†ê", "CHENG", "CHEN");
		putAmend("†§", "BIAN", "MIAN");
		putAmend("†®", "YOU", "YONG");
		putAmend("†¨", "JIU", "LE");
		putAmend("ƒ≤", "MOU", "MU");
		putAmend("†≥", "GE", "QIU");
		putAmend("†∂", "YOU", "CHOU");
		putAmend("†√", "ZHI", "TE");
		putAmend("Í˘", "JIAN", "QIAN");
		putAmend("†”", "MAO", "LI");
		putAmend("†„", "QUAN", "BA");
		putAmend("†Ê", "ZHUO", "BAO");
		putAmend("†Ë", "KANG", "GANG");
		putAmend("†È", "PEI", "FEI");
		putAmend("†Ì", "HUAN", "FAN");
		putAmend("†Ù", "YI", "QUAN", "CHI");
		putAmend("†ı", "SHENG", "XING");
		putAmend("†ˆ", "TUO", "YI");
		putAmend("™C", "HE", "MO");
		putAmend("™H", "TA", "SHI");
		putAmend("™I", "TONG", "DONG");
		putAmend("™K", "MANG", "DOU");
		putAmend("™L", "XI", "SHI");
		putAmend("™W", "BAI", "PI");
		putAmend("™\", "JIAN", "YAN");
		putAmend("™c", "YA", "WEI");
		putAmend("™m", "YA", "JIA", "QIE");
		putAmend("™n", "XIE", "HE", "GE", "HAI");
		putAmend("™p", "BIAN", "PIAN");
		putAmend("™t", "BO", "PO");
		putAmend("™Ç", "HAO", "GAO");
		putAmend("™í", "YAO", "XIAO");
		putAmend("™ì", "SHUO", "XI");
		putAmend("™ò", "GE", "LIE", "XIE");
		putAmend("™†", "BIAN", "PIAN");
		putAmend("´A", "NOU", "RU");
		putAmend("´D", "NAO", "YOU");
		putAmend("´L", "NAO", "YOU");
		putAmend("¬ ", "SHUAI", "LV");
		putAmend("´`", "CHANG", "YANG");
		putAmend("Á‰", "MIN", "WEN");
		putAmend("Á„", "BIN", "FEN");
		putAmend("´j", "MEN", "YUN");
		putAmend("´l", "JIAN", "QIAN");
		putAmend("´o", "QIANG", "CANG");
		putAmend("´q", "AN", "GAN");
		putAmend("´t", "XUAN", "XIAN");
		putAmend("´}", "YI", "TAI");
		putAmend("´~", "ZU", "JU");
		putAmend("´ê", "YIN", "KEN");
		putAmend("Áı", "HUN", "HUI");
		putAmend("´ü", "DI", "TI");
		putAmend("¨I", "XUAN", "QIONG");
		putAmend("¨V", "PIN", "BING");
		putAmend("¨X", "CUI", "SE");
		putAmend("¨^", "WEI", "YU");
		putAmend("◊¡", "ZHUO", "ZUO");
		putAmend("¨a", "BENG", "PEI");
		putAmend("¨q", "HUN", "HUI");
		putAmend("¨Ä", "XIE", "JIE");
		putAmend("¨Ñ", "CHANG", "YANG");
		putAmend("¨ô", "TIAN", "ZHEN");
		putAmend("¨ö", "QIANG", "CANG");
		putAmend("¨û", "BIN", "PIAN");
		putAmend("¨ü", "TU", "SHU");
		putAmend("≠F", "ZAO", "SUO");
		putAmend("≠W", "QIONG", "JUE");
		putAmend("≠g", "HUI", "KUAI");
		putAmend("≠o", "LU", "FU");
		putAmend("≠p", "BIN", "PIAN");
		putAmend("≠u", "JI", "ZI");
		putAmend("≠å", "MI", "XI");
		putAmend("≠é", "QIONG", "WEI");
		putAmend("≠í", "HUAN", "YE", "YA");
		putAmend("≠î", "BO", "PAO");
		putAmend("≠ï", "ZHI", "HU");
		putAmend("≠ò", "XIANG", "HONG");
		putAmend("ÆB", "BAI", "WA");
		putAmend("µÈ", "DIAN", "TIAN", "SHENG");
		putAmend("ÓÆ", "TING", "DING");
		putAmend("Æk", "TING", "DING");
		putAmend("Áﬁ", "ZAI", "ZI");
		putAmend("Æn", "BI", "QI");
		putAmend("Æw", "FU", "BI");
		putAmend("Æ}", "DA", "FU");
		putAmend("–Û", "XU", "CHU");
		putAmend("ÆÇ", "CE", "JI");
		putAmend("ÆÉ", "ZAI", "ZI");
		putAmend("Æá", "ZHI", "CHOU", "SHI");
		putAmend("Æâ", "FAN", "PAN");
		putAmend("∑¨", "FAN", "PAN");
		putAmend("Æå", "SHE", "YU");
		putAmend("ΩÆ", "JIANG", "QIANG");
		putAmend("Ò‚", "PI", "YA", "SHU");
		putAmend("ØC", "JIE", "QIE");
		putAmend("ØF", "ZHI", "DI");
		putAmend("“…", "YI", "NI");
		putAmend("∏Ì", "GE", "YI");
		putAmend("≈±", "NVE", "YAO");
		putAmend("›", "LI", "LAI");
		putAmend("ØN", "JUE", "XUE");
		putAmend("ØP", "YA", "XIA");
		putAmend("ØV", "FA", "BIAN");
		putAmend("ØZ", "SHAN", "DIAN");
		putAmend("Ø\", "TENG", "CHONG");
		putAmend("Ø_", "WEI", "YOU", "YU");
		putAmend("Øa", "TAN", "SHI");
		putAmend("Øn", "BENG", "PENG");
		putAmend("Ør", "MA", "LIN");
		putAmend("Øt", "TIAN", "DIAN");
		putAmend("Øu", "AN", "YE");
		putAmend("ØÄ", "ZHI", "CHI");
		putAmend("˝", "JIA", "XIA");
		putAmend("Øê", "HUI", "LEI");
		putAmend("˚", "CHAI", "CUO");
		putAmend("Øë", "NVE", "YAO");
		putAmend("Øí", "DIAN", "CHEN");
		putAmend("Ø†", "QIAO", "JIAO");
		putAmend("∞I", "GUI", "WEI");
		putAmend("∞O", "LI", "LAI");
		putAmend("∞n", "JI", "BI");
		putAmend("µƒ", "DI", "DE");
		putAmend("∞q", "PA", "BA");
		putAmend("∏ﬁ", "GAO", "HAO");
		putAmend("∞w", "GAO", "YAO");
		putAmend("∞ç", "LI", "LUO", "BO");
		putAmend("∞ö", "ZHA", "CU");
		putAmend("∞ú", "ZHAO", "ZHAN", "DAN");
		putAmend("∏«", "GAI", "GE", "HE");
		putAmend(" ¢", "SHENG", "CHENG");
		putAmend("±T", "ZHOU", "CHOU");
		putAmend("±Z", "MANG", "WANG");
		putAmend("±]", "XIAN", "TIAN");
		putAmend("±_", "XI", "PAN");
		putAmend(" °", "SHENG", "XING");
		putAmend("±d", "YUN", "HUN");
		putAmend("±j", "YANG", "YING");
		putAmend("±r", "JU", "XU", "KOU");
		putAmend("ÌÙ", "YI", "CHI");
		putAmend("±u", "MO", "MIE");
		putAmend("±y", "DIE", "TI");
		putAmend("±}", "BING", "FANG");
		putAmend("±~", "PANG", "PAN");
		putAmend("Ìı", "GUI", "SUI");
		putAmend("±Ç", "DIE", "ZHI");
		putAmend("±Ü", "XUAN", "SHUN", "XUN");
		putAmend("◊≈", "ZHUO", "ZHAO", "ZHE");
		putAmend("±ç", "QIAO", "SHAO", "XIAO");
		putAmend("±ë", "CUO", "ZHUAI");
		putAmend("≤B", "SUI", "ZUI");
		putAmend("≤G", "YI", "ZE", "GAO");
		putAmend("≤Z", "GUI", "WEI", "KUI");
		putAmend("≤]", "KOU", "JI");
		putAmend("≤`", "QIONG", "HUAN");
		putAmend("¬˜", "MAN", "MEN");
		putAmend("≤f", "DIAO", "DOU");
		putAmend("≤k", "LOU", "LV");
		putAmend("≤m", "MAN", "MEN");
		putAmend("≤p", "RUN", "SHUN");
		putAmend("≤v", "XIAN", "JIAN");
		putAmend("≤y", "WU", "MI");
		putAmend("≤z", "GUI", "KUI");
		putAmend("ˆƒ", "QU", "JU");
		putAmend("≤Ö", "NING", "CHENG");
		putAmend("≤à", "HUO", "YUE");
		putAmend("≤é", "KUANG", "GUO");
		putAmend("≤ï", "GUAN", "QUAN");
		putAmend("ÒÊ", "JIN", "QIN", "GUAN");
		putAmend("≤õ", "JIN", "QIN", "GUAN");
		putAmend("≤ú", "YU", "XU", "JUE");
		putAmend(" Ø", "SHI", "DAN");
		putAmend("≥M", "GANG", "QIANG", "KONG");
		putAmend("Ìπ", "XU", "HUA");
		putAmend("∆ˆ", "QI", "QIE");
		putAmend("≥W", "PIN", "BIN", "FEN");
		putAmend("≥`", "KE", "LUO");
		putAmend("Ì…", "FU", "FEI");
		putAmend("Ì«", "LI", "LA");
		putAmend("≥q", "KUANG", "GUANG");
		putAmend("≥u", "WEI", "GUI");
		putAmend("Ì—", "LUO", "GE");
		putAmend("≥w", "KEN", "XIAN", "GUN", "YIN");
		putAmend("≥y", "PENG", "PING");
		putAmend("À∂", "SHUO", "SHI");
		putAmend("≥Ç", "QUE", "KE", "KU");
		putAmend("≥â", "MANG", "BANG");
		putAmend("≥ä", "LUO", "LONG");
		putAmend("≥ã", "YONG", "TONG");
		putAmend("≥õ", "ZHUI", "CHUI", "DUO");
		putAmend("≥ü", "ZONG", "CONG");
		putAmend("¥D", "JIAN", "ZHAN");
		putAmend("¬µ", "LU", "LIU");
		putAmend("¥F", "QUE", "XI");
		putAmend("¥L", "NAO", "GANG");
		putAmend("ÌŸ", "JIE", "YA");
		putAmend("¥T", "SHUO", "SHI");
		putAmend("¥Y", "TI", "DI");
		putAmend("¥`", "QUE", "QIAO");
		putAmend("¥c", "SU", "XIE");
		putAmend("¥f", "SI", "TI");
		putAmend("∞ı", "BANG", "PANG");
		putAmend("¥h", "HUA", "KE", "GU");
		putAmend("¥j", "KUI", "WEI");
		putAmend("¥l", "XIA", "QIA", "YA");
		putAmend("¥n", "LIAN", "QIAN");
		putAmend("¥o", "AI", "WEI");
		putAmend("¥x", "AO", "QIAO");
		putAmend("¥Ñ", "QI", "ZHU");
		putAmend("¥ã", "LAO", "LUO");
		putAmend("¥ë", "PAN", "BO");
		putAmend("¥í", "JI", "SHE");
		putAmend("¥ù", "HE", "QIAO");
		putAmend("¥û", "KE", "HUO");
		putAmend("µC", "QUE", "HU");
		putAmend("µJ", "E", "QI");
		putAmend("µU", "XIAN", "XIN");
		putAmend("µo", "ZHI", "QI");
		putAmend("µp", "BENG", "FANG");
		putAmend("µz", "MI", "BI");
		putAmend("º¿", "JI", "ZHAI");
		putAmend("µà", "SHUI", "LEI");
		putAmend("Ï¯", "CHAN", "SHAN");
		putAmend("µñ", "BI", "PI");
		putAmend("∂@", "SHANG", "YANG");
		putAmend("∂A", "TI", "ZHI");
		putAmend("∂U", "SHAN", "CHAN");
		putAmend("ÿÆ", "YU", "OU");
		putAmend("∂g", "CHA", "NA");
		putAmend("∂h", "YI", "ZHI");
		putAmend("∂m", "HAO", "MAO");
		putAmend("√ÿ", "MI", "BI");
		putAmend("∂Å", "HUO", "KUO");
		putAmend("≥∆", "CHENG", "CHEN");
		putAmend("∂É", "SHI", "ZHI");
		putAmend("∂Ñ", "HUO", "KUO");
		putAmend("∂ç", "FU", "PU");
		putAmend("∂è", "XUN", "ZE");
		putAmend("∂ï", "TU", "SHU");
		putAmend("∂ù", "JI", "QI");
		putAmend("∂†", "LENG", "LING");
		putAmend("∑B", "ZUI", "ZU", "SU");
		putAmend("∑G", "XI", "QIE");
		putAmend("∑K", "PI", "BI");
		putAmend("∑Q", "CHENG", "CHEN");
		putAmend("∑S", "XIAN", "JIAN", "LIAN");
		putAmend("∑T", "ZI", "JIU");
		putAmend("ª¸", "JI", "QI");
		putAmend("∑_", "CAN", "SHAN", "CEN");
		putAmend("∑`", "MEN", "MEI");
		putAmend("∑n", "XIAO", "RAO");
		putAmend("∑q", "ZHUO", "BO");
		putAmend("∑r", "TONG", "ZHONG");
		putAmend("∑Å", "CHENG", "CHEN");
		putAmend("∑Ö", "BIAO", "PAO");
		putAmend("∑á", "ZHUO", "JUE");
		putAmend("∑â", "CUAN", "ZAN");
		putAmend("∑î", "ZHU", "KU");
		putAmend("∑ï", "JIAO", "LIAO", "LIU");
		putAmend("∑ò", "WA", "GUI");
		putAmend("Òª", "TIAO", "YAO");
		putAmend("Òø", "YIN", "XUN");
		putAmend("∏E", "YA", "YE");
		putAmend("∏K", "TIAN", "DIAN", "YAN");
		putAmend("∏S", "CHAO", "KE");
		putAmend("∏T", "KUAN", "CUAN");
		putAmend("∏U", "KUAN", "CUAN");
		putAmend("∏e", "CHU", "QI");
		putAmend("∏l", "QU", "KOU");
		putAmend("∏t", "JING", "ZHEN");
		putAmend("∏}", "CENG", "ZENG");
		putAmend("Û√", "ZHU", "DU");
		putAmend("∏Ö", "LE", "JIN");
		putAmend("∏è", "ZHUI", "RUI");
		putAmend("∏í", "CEN", "JIN", "HAN");
		putAmend("∏ì", "PI", "BI");
		putAmend("∏ó", "DA", "XIA", "NA");
		putAmend("Û–", "ZUO", "ZE");
		putAmend("πA", "FU", "FEI");
		putAmend("Ûﬁ", "YUN", "JUN");
		putAmend("πr", "POU", "BU", "FU", "PU");
		putAmend("πu", "PAI", "BEI");
		putAmend("πx", "TAI", "CHI");
		putAmend("πy", "GUAI", "DAI");
		putAmend("π|", "ZHAO", "DAO");
		putAmend("Û‰", "QING", "JING");
		putAmend("πÑ", "JUN", "QUN");
		putAmend("ÛÓ", "WAN", "YUAN");
		putAmend("πï", "SHI", "YI");
		putAmend("πñ", "YUE", "YAO", "CHUO");
		putAmend("πõ", "SHUO", "XIAO", "QIAO");
		putAmend("∫T", "GONG", "GAN", "LONG");
		putAmend("∫U", "PENG", "PANG");
		putAmend("∫[", "QIANG", "CANG");
		putAmend("∫a", "ZHU", "DI");
		putAmend("∫d", "CEN", "ZAN", "CAN");
		putAmend("∫e", "ZHUAN", "ZUAN", "SUAN");
		putAmend("∫g", "PIAO", "BIAO");
		putAmend("∫i", "TUAN", "ZHUAN");
		putAmend("∫l", "GUO", "GUI");
		putAmend("∫u", "CE", "JI");
		putAmend("∫Ä", "MI", "MIE");
		putAmend("∫ã", "SUN", "ZHUAN");
		putAmend("≤æ", "BU", "BO");
		putAmend("ªE", "ZHEN", "JIAN");
		putAmend("ªO", "FAN", "PAN", "BIAN");
		putAmend("ªP", "SOU", "SHU");
		putAmend("ª}", "SHA", "CHAO");
		putAmend("ª~", "KANG", "JING");
		putAmend("’≥", "NIAN", "ZHAN");
		putAmend("Ù“", "ZI", "CI");
		putAmend("ªê", "CE", "SE");
		putAmend("÷‡", "ZHOU", "YU");
		putAmend("Ù÷", "SAN", "SHEN");
		putAmend("ºM", "GU", "GOU");
		putAmend("√”", "MI", "MEI");
		putAmend("ºR", "SAN", "SHEN");
		putAmend("ºV", "SAN", "SHEN");
		putAmend("ÙÈ", "MI", "SI");
		putAmend("œµ", "XI", "JI");
		putAmend("ºs", "YUE", "YAO");
		putAmend("ºt", "HONG", "GONG");
		putAmend("ºv", "HE", "GE");
		putAmend("ºÅ", "JI", "JIE");
		putAmend("ºÑ", "PI", "BI");
		putAmend("ºí", "ZHA", "ZA");
		putAmend("ºô", "ZHA", "ZA");
		putAmend("ºû", "BO", "BI");
		putAmend("ΩG", "ZHEN", "TIAN");
		putAmend("Ω\", "GUA", "KUA");
		putAmend("Ω]", "BAI", "MO");
		putAmend("Ωb", "HUAN", "GENG");
		putAmend("Ωe", "XIE", "JIE");
		putAmend("Ωh", "QUAN", "SHUAN");
		putAmend("Ωj", "LUO", "LAO");
		putAmend("Ωl", "BENG", "BING", "PENG");
		putAmend("Ωo", "GEI", "JI");
		putAmend("Ωp", "TONG", "DONG");
		putAmend("Ωr", "TIAO", "DIAO", "DAO");
		putAmend("Ωw", "GAI", "HAI");
		putAmend("ΩÇ", "CHI", "ZHI");
		putAmend("ΩÉ", "MIAN", "WEN", "MAN", "WAN");
		putAmend("Ωå", "HUAN", "WAN");
		putAmend("Ωç", "QIN", "XIAN");
		putAmend("Ωû", "YAN", "XIAN");
		putAmend("æC", "ZONG", "ZENG");
		putAmend("æD", "LIN", "CHEN");
		putAmend("æF", "LI", "LIE");
		putAmend("æN", "JI", "QI");
		putAmend("æP", "QIAN", "QING", "ZHENG");
		putAmend("ÙÏ", "QING", "QI");
		putAmend("æ]", "LUN", "GUAN");
		putAmend("æb", "CHUO", "CHAO");
		putAmend("æg", "TIAN", "TAN", "CHAN");
		putAmend("æv", "LV", "LU");
		putAmend("æÉ", "JI", "QI");
		putAmend("æÖ", "CHONG", "ZHONG");
		putAmend("æà", "MIAO", "MAO");
		putAmend("æä", "XIE", "YE");
		putAmend("æñ", "TOU", "XU", "SHU");
		putAmend("æú", "BIAN", "PIAN");
		putAmend("æù", "GUN", "YUN");
		putAmend("æ†", "GUA", "WO");
		putAmend("øA", "YUN", "WEN");
		putAmend("øS", "GU", "HU");
		putAmend("øW", "CI", "CUO", "SUO");
		putAmend("øZ", "YUN", "WEN");
		putAmend("ø\", "CUI", "SUI", "SHUAI");
		putAmend("øf", "ZAI", "ZENG");
		putAmend("øh", "XIAN", "XUAN");
		putAmend("øs", "SUO", "SU");
		putAmend("øt", "YAN", "YIN");
		putAmend("øx", "ZHUAN", "JUAN");
		putAmend("ø}", "MU", "MO");
		putAmend("∑±", "FAN", "PO");
		putAmend("øä", "MOU", "MIU", "MIAO", "MU", "LIAO");
		putAmend("ÙÌ", "YAO", "YOU", "ZHOU");
		putAmend("øõ", "JU", "JUE");
		putAmend("¿M", "XI", "JI");
		putAmend("¿R", "QIAO", "SAO");
		putAmend("¿U", "JIAO", "ZHUO");
		putAmend("¿W", "DAN", "TAN", "CHAN");
		putAmend("¿b", "PU", "FU");
		putAmend("¿f", "YAO", "LI");
		putAmend("¿v", "XIANG", "RANG");
		putAmend("¿{", "LI", "XI", "SA");
		putAmend("∫Ï", "HONG", "GONG");
		putAmend("œÀ", "XIAN", "QIAN");
		putAmend("Ê¸", "HE", "GE");
		putAmend("‘º", "YUE", "YAO");
		putAmend("Á¢", "PI", "BI");
		putAmend("¬⁄", "LUN", "GUAN");
		putAmend("∏¯", "GEI", "JI");
		putAmend("¬Á", "LUO", "LAO");
		putAmend("¥¬", "CHUO", "CHAO");
		putAmend("◊€", "ZONG", "ZENG");
		putAmend("¬Ã", "LV", "LU");
		putAmend("º©", "JI", "QI");
		putAmend("¿à", "YUN", "WEN");
		putAmend("Á¬", "BIAN", "PIAN");
		putAmend("¿ä", "CUI", "SUI", "SHUAI");
		putAmend("Àı", "SUO", "SU");
		putAmend("Á—", "MOU", "MIU", "MIAO", "MU", "LIAO");
		putAmend("Áÿ", "QIAO", "SAO");
		putAmend("Ω…", "JIAO", "ZHUO");
		putAmend("∞’", "BA", "PI");
		putAmend("¡L", "GUAI", "GUA");
		putAmend("¡T", "BA", "PI");
		putAmend("—Ú", "YANG", "XIANG");
		putAmend("¡f", "YANG", "XIANG");
		putAmend("¡o", "MEI", "GAO");
		putAmend("¡p", "YI", "XI");
		putAmend("¡z", "QIANG", "KONG");
		putAmend("¡{", "QIAN", "XIAN", "YAN");
		putAmend("¡á", "HONG", "GONG");
		putAmend("¡ë", "PI", "BI", "PO");
		putAmend("¡î", "QU", "YU");
		putAmend("µ‘", "DI", "ZHAI");
		putAmend("¡ü", "DAO", "ZHOU");
		putAmend("¬J", "HOU", "QU");
		putAmend("Í»", "QI", "SHI");
		putAmend("¬X", "RUAN", "NUO");
		putAmend("¬Y", "ER", "NAI");
		putAmend("¬Z", "DUAN", "ZHUAN");
		putAmend("∞“", "BA", "PA");
		putAmend("¬]", "SI", "CHI");
		putAmend("¬^", "QU", "CHU");
		putAmend("¬c", "JI", "JIE");
		putAmend("¬d", "ZHA", "ZE");
		putAmend("¬m", "YUN", "YING");
		putAmend("¬v", "WA", "TUI", "ZHUO");
		putAmend("¬x", "ER", "NV");
		putAmend("¬z", "TIE", "ZHE");
		putAmend("¬Ç", "DI", "ZHI");
		putAmend("¬û", "NI", "JIAN");
		putAmend("¿ﬂ", "LEI", "LE");
		putAmend("√J", "BO", "DI");
		putAmend("Î¿", "RONG", "CHEN");
		putAmend("√Q", "QIN", "HAN");
		putAmend("√T", "PANG", "PAN");
		putAmend("Î∆", "ZHUN", "CHUN");
		putAmend("√Y", "PI", "BI");
		putAmend("√^", "FEI", "BI");
		putAmend("√c", "ZI", "FEI");
		putAmend("√d", "FEI", "KU");
		putAmend("√g", "PING", "PENG");
		putAmend("√i", "FU", "ZHOU");
		putAmend("≈÷", "PANG", "PAN");
		putAmend("ƒ‹", "NENG", "NAI");
		putAmend("√v", "GUI", "KUI");
		putAmend("¬ˆ", "MAI", "MO");
		putAmend("Ω≈", "JIAO", "JUE");
		putAmend("ƒr", "LU", "BIAO");
		putAmend("ƒx", "ZHUAN", "CHUAN", "CHUN");
		putAmend("ƒá", "FAN", "PAN");
		putAmend("ƒä", "HU", "WU");
		putAmend("Î˛", "SHAN", "DAN");
		putAmend("±€", "BI", "BEI");
		putAmend("ƒó", "LA", "GE");
		putAmend("ƒü", "WO", "YUE");
		putAmend("≈M", "NI", "LUAN");
		putAmend("≈O", "QIAN", "XIAN");
		putAmend("≈Q", "GUANG", "JIONG");
		putAmend("Í∞", "ZANG", "CANG");
		putAmend("≈S", "GUANG", "JIONG");
		putAmend("≥Ù", "CHOU", "XIU");
		putAmend("≈X", "MIAN", "BIAN");
		putAmend("≈\", "DIE", "ZHI");
		putAmend("≈]", "ZHI", "JIN");
		putAmend("…´", "SE", "SHAI");
		putAmend("∞¨", "AI", "YI");
		putAmend("∆O", "CHAI", "CHA");
		putAmend("∆S", "HU", "XIA");
		putAmend("∆U", "HUI", "HU");
		putAmend("‹≈", "BI", "PI");
		putAmend("∆X", "TUN", "CHUN");
		putAmend("ΩÊ", "JIE", "GAI");
		putAmend("∆^", "XU", "ZHU");
		putAmend("‹æ", "YUAN", "YAN");
		putAmend("∆_", "LUN", "HUA");
		putAmend("‹Ã", "WU", "HU");
		putAmend("‹¿", "FEI", "FU");
		putAmend("∆g", "CHAN", "YIN");
		putAmend("∆l", "DI", "TI");
		putAmend("Ã¶", "TAI", "TA");
		putAmend("‹Ê", "TIAO", "SHAO");
		putAmend("∆n", "LI", "JI");
		putAmend("ø¡", "KE", "HE");
		putAmend("‹ƒ", "JU", "QU");
		putAmend("∆r", "ZHU", "NING");
		putAmend("∆t", "PA", "BO");
		putAmend("∆z", "ZUO", "ZHA");
		putAmend("‹⁄", "JU", "CHA");
		putAmend("∆Å", "SHENG", "RUI");
		putAmend("«—", "QIE", "JIA");
		putAmend("›°", "QIAN", "XUN");
		putAmend("…Ø", "SUO", "SHA");
		putAmend("«l", "PENG", "FENG");
		putAmend("›∑", "SHEN", "XIN");
		putAmend("›∏", "GUAN", "WAN");
		putAmend("«x", "SU", "YOU");
		putAmend("«z", "SHAO", "XIAO");
		putAmend("›π", "LANG", "LIANG");
		putAmend("›≥", "FU", "PIAO");
		putAmend("«|", "WEN", "WAN", "MIAN");
		putAmend("›≤", "XIAN", "LIAN");
		putAmend("›“", "WAN", "YUN");
		putAmend("«à", "ZOU", "CHU");
		putAmend("«å", "NIE", "REN");
		putAmend("«è", "ZI", "ZAI");
		putAmend("«ù", "JIE", "SHA");
		putAmend("«ü", "QIAO", "ZHAO");
		putAmend("«†", "TAI", "ZHI", "CHI");
		putAmend("»B", "QIN", "JIN");
		putAmend("»H", "LIN", "MA");
		putAmend("¬‰", "LUO", "LA");
		putAmend("÷¯", "ZHU", "ZHE", "ZHUO");
		putAmend("›ÿ", "SHEN", "REN");
		putAmend("›ﬁ", "KUI", "KUAI");
		putAmend("…S", "RU", "NA");
		putAmend("…V", "YUAN", "HUAN");
		putAmend("…[", "XU", "SHU");
		putAmend("…a", "ZU", "JU");
		putAmend("…w", "GAI", "GE", "HE");
		putAmend("…|", "YAO", "ZHUO");
		putAmend("…â", "DIAO", "TIAO", "DI");
		putAmend("…í", "QIU", "XU", "FU");
		putAmend("…õ", "ZI", "JU");
		putAmend("ﬁ§", "LIAO", "LU");
		putAmend("¬˚", "MAN", "WAN");
		putAmend("À@", "XI", "XIAO");
		putAmend("±°", "BO", "BAO");
		putAmend("ÀF", "CI", "ZI");
		putAmend("ÀH", "WAN", "LUAN");
		putAmend("ÀN", "QIANG", "SE");
		putAmend("ÀW", "XIAN", "LIAN");
		putAmend("À^", "HAO", "KAO");
		putAmend("Àe", "YUAN", "WEI");
		putAmend("Àg", "CHOU", "ZHOU");
		putAmend("Àh", "MAI", "WO");
		putAmend("Àj", "JI", "QI");
		putAmend("Àr", "XIAO", "HAO");
		putAmend("Àv", "XU", "YU");
		putAmend("ΩÂ", "JIE", "JI");
		putAmend("Ày", "DIAO", "ZHUO");
		putAmend("≤ÿ", "ZANG", "CANG");
		putAmend("Àë", "BIAO", "PAO");
		putAmend("À†", "ZHU", "CHU");
		putAmend("∫Á", "HONG", "JIANG");
		putAmend("œ∫", "XIA", "HA");
		putAmend("ÕK", "FANG", "BANG");
		putAmend("∞ˆ", "BANG", "BENG");
		putAmend("ÕV", "QI", "ZHI");
		putAmend("ÕW", "YUAN", "WAN");
		putAmend("ÕX", "JUE", "QUE");
		putAmend("ÕZ", "QIN", "QIAN");
		putAmend("Úº", "GONG", "ZHONG");
		putAmend("Õf", "DAI", "DE");
		putAmend("Õm", "GOU", "QU", "XU");
		putAmend("Õo", "PI", "BO");
		putAmend("…ﬂ", "SHE", "YI");
		putAmend("Õx", "GE", "LUO");
		putAmend("Õ{", "MANG", "BANG");
		putAmend("ÕÇ", "YI", "XU");
		putAmend("∏Ú", "GE", "HA");
		putAmend("Õâ", "QIE", "NI");
		putAmend("∂Í", "E", "YI");
		putAmend("Œâ", "XI", "QI");
		putAmend("Œì", "BI", "PI");
		putAmend("Œó", "NAI", "NENG");
		putAmend("Œò", "HE", "XIA");
		putAmend("Œö", "GUI", "HUI");
		putAmend("Ûß", "SHI", "ZHE");
		putAmend("œH", "DIE", "ZHI");
		putAmend("œJ", "QU", "JU");
		putAmend("œM", "CHAN", "JIAN");
		putAmend("Ú˛", "MANG", "MENG");
		putAmend("œn", "FEI", "BEN");
		putAmend("œo", "LAO", "LIAO");
		putAmend("œr", "YIN", "XUN");
		putAmend("—™", "XUE", "XIE");
		putAmend("––", "XING", "HANG", "HENG");
		putAmend("–à", "BAO", "PAO");
		putAmend("–ç", "JU", "JIE");
		putAmend("–é", "HE", "KE");
		putAmend("–ú", "NA", "JUE");
		putAmend("±ª", "BEI", "PI");
		putAmend("—D", "CHI", "NUO");
		putAmend("—E", "CHI", "QI", "DUO", "NUO");
		putAmend("Ò ", "JIA", "JIE", "QIA");
		putAmend("—I", "JIAN", "ZUN");
		putAmend("—J", "BO", "MO");
		putAmend("—O", "GUI", "GUA");
		putAmend("—\", "GE", "JIE");
		putAmend("Ò‘", "BI", "PI");
		putAmend("—n", "CHOU", "DAO");
		putAmend("…—", "CHANG", "SHANG");
		putAmend("—r", "YUAN", "GUN");
		putAmend("Ò”", "XI", "TI");
		putAmend("Ò˚", "TAN", "QIN");
		putAmend("“ä", "JIAN", "XIAN");
		putAmend("“è", "JUE", "JIAO");
		putAmend("“î", "PIE", "MIE");
		putAmend("“ô", "JUE", "JIAO");
		putAmend("”H", "QIN", "QING");
		putAmend("”S", "JIAN", "BIAN");
		putAmend("”T", "LUO", "LUAN");
		putAmend("”X", "JUE", "JIAO");
		putAmend("º˚", "JIAN", "XIAN");
		putAmend("æı", "JUE", "JIAO");
		putAmend("Ω«", "JIAO", "JUE");
		putAmend("ı˛", "ZI", "ZUI");
		putAmend("”i", "HUA", "XIE");
		putAmend("Ω‚", "JIE", "XIE");
		putAmend("”n", "JIE", "XIE");
		putAmend("”s", "JI", "QI");
		putAmend("”{", "XUE", "HU");
		putAmend("”Ä", "LI", "LU");
		putAmend("’A", "TIAO", "DIAO");
		putAmend("’B", "YI", "CHI");
		putAmend("’O", "EI", "XI");
		putAmend("’R", "BEI", "BO");
		putAmend("’f", "SHUO", "SHUI", "YUE");
		putAmend("’h", "SHUO", "SHUI", "YUE");
		putAmend("’l", "SHUI", "SHEI");
		putAmend("’o", "QU", "JUE");
		putAmend("’v", "CHI", "LAI");
		putAmend("’y", "NI", "NA");
		putAmend("’{", "DIAO", "TIAO");
		putAmend("’|", "PI", "BEI");
		putAmend("’ã", "ZE", "ZUO", "ZHA", "CUO");
		putAmend("’ë", "CHU", "JI");
		putAmend("’í", "XIA", "HAO");
		putAmend("’ú", "SHI", "DI");
		putAmend("’†", "HUA", "GUA");
		putAmend("÷L", "XI", "SHAI");
		putAmend("◊z", "JUAN", "XUAN");
		putAmend("◊Ç", "YI", "TUI");
		putAmend("–Ì", "XU", "HU");
		putAmend(" ∂", "SHI", "ZHI");
		putAmend("⁄±", "YI", "DAI");
		putAmend("⁄µ", "JIE", "JI");
		putAmend("◊û", "ZHOU", "CHOU");
		putAmend("Àµ", "SHUO", "SHUI", "YUE");
		putAmend("⁄¿", "EI", "XI");
		putAmend("µ˜", "DIAO", "TIAO");
		putAmend("π»", "GU", "YU");
		putAmend("ÿ~", "KEN", "KUN");
		putAmend("ÿÄ", "HE", "MO");
		putAmend("∫—", "HE", "HAO", "MO");
		putAmend("ÿã", "JU", "LOU");
		putAmend("ÿí", "YUAN", "YUN");
		putAmend("ÿü", "ZE", "ZHAI");
		putAmend("ŸS", "BI", "BEN");
		putAmend("ŸZ", "JIA", "GU");
		putAmend("ŸÇ", "XIONG", "MIN");
		putAmend("Ÿç", "ZHUAN", "ZUAN");
		putAmend("⁄g", "DIE", "TU");
		putAmend("ÙÚ", "QIE", "JU");
		putAmend("«˜", "QU", "CU");
		putAmend("⁄l", "JI", "JIE");
		putAmend("⁄o", "GUA", "HUO");
		putAmend("⁄|", "QUE", "QI", "JI");
		putAmend("»§", "QU", "CU");
		putAmend("⁄Ö", "QU", "CU");
		putAmend("⁄å", "TI", "YUE");
		putAmend("ı¿", "BAO", "BO");
		putAmend("⁄è", "KUA", "WU");
		putAmend("⁄ë", "JUE", "GUI");
		putAmend("⁄ì", "FANG", "PANG");
		putAmend("⁄ï", "BA", "PAO");
		putAmend("⁄ô", "JIAN", "CHEN");
		putAmend("€@", "DIAN", "TIE", "DIE");
		putAmend("€A", "PAN", "BAN");
		putAmend("€B", "JU", "QIE");
		putAmend("ı»", "LI", "LUO");
		putAmend("€F", "DAI", "DUO", "CHI");
		putAmend("€M", "PIAN", "BENG");
		putAmend("Ã¯", "TIAO", "TAO");
		putAmend("€S", "SHU", "CHOU");
		putAmend("ıË", "QI", "XI");
		putAmend("‹V", "LI", "LUO");
		putAmend("‹a", "SA", "XIE");
		putAmend("‹á", "CHE", "JU");
		putAmend("‹à", "YA", "ZHA", "GA");
		putAmend("‹å", "XIN", "XIAN");
		putAmend("‹è", "FAN", "GUI");
		putAmend("›W", "YI", "DIE");
		putAmend("≥µ", "CHE", "JU");
		putAmend("‘˛", "ZHA", "YA");
		putAmend("’∑", "ZHAN", "NIAN");
		putAmend("±Ÿ", "BI", "PI");
		putAmend("ﬁx", "DAO", "BIAN");
		putAmend("ﬁÇ", "WANG", "KUANG");
		putAmend("ªπ", "HUAN", "HAI");
		putAmend("’‚", "ZHE", "ZHEI");
		putAmend("ﬁå", "ZHI", "LI");
		putAmend("∆»", "PAI", "PO");
		putAmend("ﬁé", "ZHU", "WANG");
		putAmend("ﬂÄ", "HUAN", "HAI");
		putAmend("ﬂÜ", "LI", "CHI");
		putAmend("ﬂí", "KANG", "HANG");
		putAmend("ƒ«", "NA", "NEI");
		putAmend("‡@", "GAI", "HAI");
		putAmend("€ß", "QIE", "XI");
		putAmend("€®", "XUN", "HUAN");
		putAmend("€™", "LI", "ZHI");
		putAmend("∂º", "DU", "DOU");
		putAmend("·]", "TAN", "DAN");
		putAmend("·b", "QIU", "CHOU");
		putAmend("·e", "PO", "FA");
		putAmend("·p", "CHAN", "CHEN");
		putAmend("·w", "PO", "FA");
		putAmend("·y", "YI", "SHI");
		putAmend("·z", "YAN", "LIAN", "XIAN");
		putAmend("÷ÿ", "ZHONG", "CHONG");
		putAmend("·ç", "LI", "XI");
		putAmend("·†", "QIAO", "JIAO");
		putAmend("‚D", "HUA", "YU");
		putAmend("‚E", "HUA", "WU");
		putAmend("‚J", "RI", "REN", "JIAN");
		putAmend("‚K", "DI", "DAI");
		putAmend("‚P", "SHI", "YI");
		putAmend("‚V", "RI", "REN", "JIAN");
		putAmend("‚W", "PI", "ZHAO");
		putAmend("‚X", "YE", "YA");
		putAmend("„}", "XIANG", "JIONG");
		putAmend("„É", "YU", "SI");
		putAmend("„Ñ", "XU", "HUI");
		putAmend("„à", "SHAN", "SHUO");
		putAmend("„â", "CHI", "LI");
		putAmend("„ä", "XIAN", "XI");
		putAmend("„ê", "HOU", "XIANG");
		putAmend("„ì", "DIAO", "TIAO", "YAO");
		putAmend("„î", "XIAN", "KUO", "TIAN", "GUA");
		putAmend("‰K", "SHI", "ZHI");
		putAmend("‰O", "ZHE", "NIE");
		putAmend("‰T", "XIAN", "KUO", "TIAN", "GUA");
		putAmend("‰U", "HONG", "GONG");
		putAmend("‰V", "ZHONG", "YONG");
		putAmend("‰W", "TOU", "TU", "DOU");
		putAmend("‰Y", "MEI", "MENG");
		putAmend("‰[", "WAN", "JIAN");
		putAmend("‰b", "TING", "DING");
		putAmend("‰g", "JUAN", "JIAN", "CUAN");
		putAmend("‰l", "SI", "TUO");
		putAmend("‰m", "XUAN", "JUAN");
		putAmend("‰n", "HUA", "WU");
		putAmend("‰r", "ZHUO", "CHUO");
		putAmend("‰t", "XING", "JING");
		putAmend("‰é", "ZUI", "NIE");
		putAmend("‰ë", "YUAN", "WAN");
		putAmend("Ê\", "CUO", "CHA");
		putAmend("Ê]", "DA", "TA");
		putAmend("Êa", "SUO", "SE");
		putAmend("Êc", "YAO", "ZU");
		putAmend("Êd", "YE", "TA", "GE");
		putAmend("Êj", "QIANG", "CHENG");
		putAmend("Êk", "GE", "LI");
		putAmend("Êq", "BI", "PI");
		putAmend("Ê~", "WAN", "JIAN");
		putAmend("ÊÄ", "GAO", "HAO");
		putAmend("Êó", "ZU", "CHUO");
		putAmend("Êù", "SHOU", "SOU");
		putAmend("ÁD", "SAN", "QIAO", "CAN");
		putAmend("ÁG", "LU", "AO");
		putAmend("ÁZ", "JIAN", "ZAN");
		putAmend("Ái", "HUI", "SUI", "RUI");
		putAmend("Áo", "SAN", "XIAN", "SA");
		putAmend("Ëï", "SA", "XI");
		putAmend("‘ø", "YUE", "YAO");
		putAmend("ÓŸ", "BA", "PA");
		putAmend("Ó‰", "DIAN", "TIAN");
		putAmend("«¶", "QIAN", "YAN");
		putAmend("ÓË", "TA", "TUO");
		putAmend("Óı", "DANG", "CHENG");
		putAmend("œ≥", "XIAN", "XI");
		putAmend("Ó˙", "TING", "DING");
		putAmend("Ëù", "XIAN", "KUO", "TIAN", "GUA");
		putAmend("Ó˛", "HA", "KE");
		putAmend("Ô¢", "DIAO", "TIAO", "YAO");
		putAmend("≥§", "ZHANG", "CHANG");
		putAmend("ÈX", "HUO", "SHAN");
		putAmend("È\", "HAN", "BI");
		putAmend("Èf", "XIAN", "JIAN");
		putAmend("Èp", "XIA", "KE");
		putAmend("Èr", "BIAN", "GUAN");
		putAmend("Èx", "HE", "GE");
		putAmend("È{", "HONG", "XIANG");
		putAmend("Èë", "E", "YAN");
		putAmend("Èó", "HONG", "JUAN", "XIANG");
		putAmend("Èõ", "BAN", "PAN");
		putAmend("ÍA", "DU", "SHE");
		putAmend("ÍO", "TANG", "CHANG");
		putAmend("ÍR", "KAN", "HAN");
		putAmend("ÍS", "XI", "SE", "TA");
		putAmend("Í\", "HAN", "BI");
		putAmend("∞¢", "E", "A");
		putAmend("Ωµ", "XIANG", "JIANG");
		putAmend("Íú", "YU", "YAO", "SHU");
		putAmend("Í†", "DUI", "ZHUI");
		putAmend("ÀÂ", "SUI", "DUO");
		putAmend("ÎB", "QI", "GAI");
		putAmend("ÎD", "HUI", "DUO");
		putAmend("⁄Û", "WEI", "KUI");
		putAmend("ÎT", "AO", "YU");
		putAmend("„ƒ", "HUI", "DUO");
		putAmend("ˆø", "ZHUI", "CUI", "WEI");
		putAmend("Îa", "HU", "HE");
		putAmend("ˆ¡", "JUN", "JUAN");
		putAmend("ƒ—", "NAN", "NUO");
		putAmend("»∏", "QUE", "QIAO");
		putAmend("Îh", "JUN", "JUAN");
		putAmend("Îq", "GUAN", "HUAN");
		putAmend("Îv", "GUI", "XI");
		putAmend("Îy", "NAN", "NUO");
		putAmend("ÎÅ", "SE", "XI");
		putAmend("Îâ", "WU", "MENG");
		putAmend("¬∂", "LOU", "LU");
		putAmend("∏Ô", "GE", "JI");
		putAmend("Ïë", "GE", "TA", "SA");
		putAmend("Ïì", "JIE", "JI");
		putAmend("˜¥", "MAN", "MEN");
		putAmend("Ïô", "BIAN", "YING");
		putAmend("« ", "QIAO", "SHAO");
		putAmend("Ïú", "XUAN", "JUAN");
		putAmend("Ï†", "SHANG", "ZHANG");
		putAmend("Ì@", "BING", "PI", "BI", "BEI");
		putAmend("ÌC", "XIE", "DIE");
		putAmend("ÌJ", "MU", "MOU");
		putAmend("ÌM", "WEN", "YUN");
		putAmend("ÌS", "BI", "BING");
		putAmend("Ìi", "MEI", "WA");
		putAmend("Ìs", "SHE", "XIE");
		putAmend("Ëπ", "YUN", "WEN");
		putAmend("æ±", "JING", "GENG");
		putAmend("Ú°", "JIE", "XIE", "JIA");
		putAmend("Ú¢", "HE", "GE");
		putAmend("∆µ", "PIN", "BIN");
		putAmend("≤¸", "CHAN", "ZHAN");
		putAmend("ÔM", "BIAO", "DIU");
		putAmend("ÔT", "BA", "FU");
		putAmend("Ôb", "SAO", "SOU");
		putAmend("Ôf", "LIU", "LIAO");
		putAmend(" ≥", "SHI", "SI", "YI");
		putAmend("ÔÖ", "YANG", "JUAN");
		putAmend("Ôå", "ZHU", "TOU");
		putAmend("Ôç", "YI", "SI");
		putAmend("Ôé", "ZUO", "ZE", "ZHA");
		putAmend("ÒN", "YUN", "WO");
		putAmend("ÒT", "FENG", "PING");
		putAmend("ÒW", "TUO", "DUO");
		putAmend("ÒX", "TUO", "ZHE");
		putAmend("Ò\", "ZHI", "SHI");
		putAmend("Ò^", "XIN", "JIN");
		putAmend("Òi", "JUE", "KUAI");
		putAmend("Òj", "TUO", "DUO");
		putAmend("Ò~", "TAI", "DAI");
		putAmend("Òè", "XUN", "XUAN");
		putAmend("Ú@", "LIANG", "LANG");
		putAmend("ÊÙ", "PIAO", "BIAO");
		putAmend("Ûc", "BEI", "MO");
		putAmend("Ûf", "QIAO", "XIAO");
		putAmend("Ûp", "BO", "JUE");
		putAmend("Ûè", "BI", "PO");
		putAmend("Ûê", "MAO", "MENG");
		putAmend("Ûñ", "KUO", "YUE");
		putAmend("ıJ", "CI", "JI");
		putAmend("ıN", "BO", "BA");
		putAmend("ıi", "LUO", "GE");
		putAmend("ıq", "GUI", "XIE");
		putAmend("ıã", "PU", "BU");
		putAmend("ˆG", "YI", "SI");
		putAmend("˜Ö", "HE", "GE");
		putAmend("˜à", "BO", "BA");
		putAmend("ˆŸ", "GUI", "XIE");
		putAmend("»˙", "SAI", "XI");
		putAmend("˜¨", "GUI", "JUE");
		putAmend("¯@", "ZHAN", "SHAN");
		putAmend("¯B", "NIAO", "DIAO");
		putAmend("¯J", "DIAO", "ZHAO");
		putAmend("¯N", "GAN", "HAN", "YAN");
		putAmend("¯W", "FU", "GUI");
		putAmend("¯X", "BAN", "FEN");
		putAmend("¯Z", "JIAN", "QIAN", "ZHAN");
		putAmend("˘ï", "TI", "CHI");
		putAmend("˘ó", "TI", "CHI");
		putAmend("˘õ", "FU", "BI");
		putAmend("˘ü", "HE", "JIE");
		putAmend("˙@", "PIAN", "BIAN");
		putAmend("˙E", "CHUAN", "ZHI");
		putAmend("˙I", "CANG", "QIANG");
		putAmend("˙K", "HE", "HU");
		putAmend("˙X", "GU", "HU");
		putAmend("˙Z", "SUN", "XUN");
		putAmend("˙y", "LOU", "LV");
		putAmend("˚Å", "PAO", "BIAO");
		putAmend("˚Ñ", "ZHU", "CU");
		putAmend("˜Â", "JUN", "QUN");
		putAmend("¸N", "MO", "ME");
		putAmend("˜·", "MO", "ME", "MA");
		putAmend("¸l", "DAN", "SHEN");
		putAmend("¸m", "ZHEN", "YAN");
		putAmend("¸r", "DAN", "ZHAN");
		putAmend("¸w", "MIN", "MIAN", "MENG");
		putAmend("ˆº", "MIN", "MIAN", "MENG");
		putAmend("˝á", "YIN", "KEN");
		putAmend("ˆ∏", "YIN", "KEN");
		putAmend("˝ä", "GONG", "WO");
		putAmend("˝î", "GUI", "JUN", "QIU");
		putAmend("πÍ", "GUI", "QIU", "JUN");

	}

	private volatile static HanziToPinyin HANZI;
	private volatile Context mContext;

	public synchronized static final HanziToPinyin install(Context context) {
		if (HANZI == null) {
			HANZI = new HanziToPinyin(context);
		}
		return HANZI;
	}

	private HanziToPinyin(Context context) {
		try {
			mContext = context;
		} catch (Exception e) {
			e.printStackTrace();
		}
	}

	public static final char MIN_HANZI = '\u4E00';
	public static final char MAX_HANZI = '\u9fa5';

	public Object[] getPinyin(String input, ResultRuler rule) {
		InputStream inputStream = null;

		Object[] objs = new Object[2];
		objs[0] = false;
		String[] data = new String[input.length()];
		StringBuilder content = new StringBuilder(6);
		int length = input.length();
		int count = 0;
		for (int i = 0; i < length; i++) {
			char letter = Character.toUpperCase(input.charAt(i));
			int skipCount = letter - MIN_HANZI;
			if (skipCount >= 0 && letter <= MAX_HANZI) {
				if (content.length() != 0) {
					data[count] = content.toString();
					content.setLength(0);
					count++;
				}
				int result = Collections.binarySearch(AMEND, letter + "", AMEND_BIN_COMP);
				if (result >= 0) {
					objs[0] = true;
					String[] mList = AMEND.get(result);
					for (int j = 1; j < mList.length; j++) {
						String mStr = mList[j];
						content.append((j == 1 ? "" : " ") + mStr);
					}
				} else {
					try {
						inputStream = mContext.getResources().openRawResource(R.raw.hanzi);
						inputStream.skip(skipCount * 6);
						int code;
						while ((code = inputStream.read()) != -1 && code != ' ') {
							content.append(Character.toUpperCase((char) code));
						}
					} catch (IOException e) {
						content.append(letter);
					} finally {
						close(inputStream);
					}
				}

			} else if ((letter < '0' || letter > '9') && (letter < 'A' || letter > 'Z') && rule != null
					&& !rule.isEnable(letter)) {
				if (content.length() != 0) {
					data[count] = content.toString();
					content.setLength(0);
					count++;
				}
				content.append(" ");
			} else {
				content.append(letter);
				continue;
			}
			data[count] = content.toString();
			content.setLength(0);
			count++;
		}

		if (content.length() != 0) {
			data[count] = content.toString();
			content.setLength(0);
			count++;
		}

		if (count != data.length) {
			String[] newData = new String[count];
			System.arraycopy(data, 0, newData, 0, count);
			data = newData;
		}
		objs[1] = data;
		return objs;
	}

	public String getPinyin(String input, ResultRuler limit, String spac) {
		InputStream inputStream = null;

		StringBuilder sb = new StringBuilder(6);
		StringBuilder content = new StringBuilder(6);
		int length = input.length();

		for (int i = 0; i < length; i++) {
			char letter = Character.toUpperCase(input.charAt(i));
			int skipCount = letter - MIN_HANZI;

			if (skipCount >= 0 && letter <= MAX_HANZI) {
				if (content.length() != 0) {
					sb.append(content.toString());
					sb.append(spac);
					content.setLength(0);
				}
				int result = Collections.binarySearch(AMEND, letter + "", AMEND_BIN_COMP);
				if (result >= 0) {
					String[] mList = AMEND.get(result);
					content.append(mList[1]);
					for (int j = 2; j < mList.length; j++) {
						content.append(" ");
						content.append(mList[j]);
					}
				} else {
					try {
						inputStream = mContext.getResources().openRawResource(R.raw.hanzi);
						inputStream.skip(skipCount * 6);
						int code;
						while ((code = inputStream.read()) != -1 && code != ' ') {
							content.append(Character.toUpperCase((char) code));
						}
					} catch (IOException e) {
						content.append(letter);
					} finally {
						close(inputStream);
					}
				}
			} else if ((letter < '0' || letter > '9') && (letter < 'A' || letter > 'Z') && limit != null
					&& !limit.isEnable(letter)) {
				if (content.length() != 0) {
					sb.append(content.toString());
					sb.append(spac);
					content.setLength(0);
				}
				content.append(" ");
			} else {
				content.append(letter);
				continue;
			}
			sb.append(content.toString());
			sb.append(spac);
			content.setLength(0);
		}

		if (content.length() != 0) {
			sb.append(content.toString());
			sb.append(spac);
			content.setLength(0);
		}
		return sb.toString();

	}

	public static PinyinName getPinyinNameObject(boolean hasT9, ResultRuler ruleNumber, String input,
			ResultRuler rulePinyin) {
		return new PinyinName(hasT9, input, ruleNumber, rulePinyin);
	}

	public static Pinyin getPinyinObject(boolean hasT9, ResultRuler t9limit, String input, ResultRuler rule) {
		Object[] objs = getPinyins(input, rule);
		return new Pinyin(hasT9, (Boolean) objs[0], (String[]) objs[1], t9limit);
	}

	public static Object[] getPinyins(String input, ResultRuler rule) {
		if (HANZI != null) {
			return HANZI.getPinyin(input, rule);
		}
		return null;
	}

	public static String getPinyins(String input, ResultRuler limit, String spac) {
		if (HANZI != null) {
			return HANZI.getPinyin(input, limit, spac);
		}
		return null;
	}

	public static String[] getPinYinT9Number(String[] pinyins, ResultRuler ruleNumber) {

		if (ruleNumber == null) {
			ruleNumber = ResultRuler.S_RULER;
		}

		pinyins = pinyins.clone();
		StringBuilder sb = new StringBuilder();
		int length;
		String letters;
		char zeor = Character.toUpperCase('0');
		char nine = Character.toUpperCase('9');

		for (int i = 0; i < pinyins.length; i++) {
			letters = pinyins[i];
			length = letters.length();
			for (int j = 0; j < length; j++) {
				char c = letters.charAt(j);
				if (c < zeor || c > nine) {
					c = ruleNumber.getLetterMap(c);
				}
				sb.append(c);
			}
			pinyins[i] = sb.toString();
			sb.setLength(0);
		}
		return pinyins;
	}

	private static void close(Closeable... close) {
		for (Closeable c : close) {
			if (c != null) {
				try {
					c.close();
				} catch (IOException e) {
					e.printStackTrace();
				}
			}
		}
	}

	public static class ResultRuler {

		public static final ResultRuler S_RULER = new ResultRuler();

		public boolean isEnable(char c) {
			return Character.isLetterOrDigit(c);
		}

		public String getStringMapFromNumber(char c) {
			switch (c) {
			case '2':
				return "ABC";
			case '3':
				return "DEF";
			case '4':
				return "GHI";
			case '5':
				return "JKL";
			case '6':
				return "MNO";
			case '7':
				return "PQRS";
			case '8':
				return "TUV";
			case '9':
				return "WXYZ";
			}
			return null;
		}

		public char getLetterMap(char c) {
			if (c >= 65 && c <= 90) {
				if (c <= 67)
					return '2';
				else if (c <= 70)
					return '3';
				else if (c <= 73)
					return '4';
				else if (c <= 76)
					return '5';
				else if (c <= 79)
					return '6';
				else if (c <= 83)
					return '7';
				else if (c <= 86)
					return '8';
				else if (c <= 90)
					return '9';
			}
			return ' ';
		}

	}

	public static final class PinyinName implements Comparable<Pinyin> {
		public final String name;
		public final String[] pinyin;
		public final String[] number;
		public final boolean more;
		public final char initial;

		public PinyinName(String name) {
			this(true, name, ResultRuler.S_RULER, ResultRuler.S_RULER);
		}

		public PinyinName(String name, ResultRuler rulePinyin) {
			this(true, name, rulePinyin, null);
		}

		public PinyinName(String name, ResultRuler rulePinyin, ResultRuler ruleNumber) {
			this(true, name, rulePinyin, ruleNumber);
		}

		public PinyinName(boolean hasNumber, String name, ResultRuler rulePinyin, ResultRuler ruleNumber) {
			Object[] objs = getPinyins(name, rulePinyin);
			this.name = name;
			this.more = (Boolean) objs[0];
			this.pinyin = (String[]) objs[1];
			this.initial = pinyin[0].charAt(0);
			this.number = hasNumber ? getPinYinT9Number(pinyin, ruleNumber) : null;
		}

		@Override
		public int compareTo(Pinyin o) {
			return 0;
		}
	}

	public static final class Pinyin implements Comparable<Pinyin> {
		public final String[] pinyin;
		public final String[] number;
		public final boolean more;
		public final char initial;

		private boolean hasMore(String[] pinyin) {
			for (int i = 0; i < pinyin.length; i++) {
				if (pinyin[i].indexOf(" ") > 0) {
					return true;
				}
			}
			return false;
		}

		public Pinyin(boolean hasNumber, String[] pinyin, ResultRuler limitnumber) {
			this.more = hasMore(pinyin);
			this.pinyin = pinyin;
			this.initial = pinyin[0].charAt(0);
			this.number = hasNumber ? getPinYinT9Number(pinyin, limitnumber) : null;
		}

		public Pinyin(boolean hasNumber, boolean more, String[] pinyin, ResultRuler limitnumber) {
			this.more = more;
			this.pinyin = pinyin;
			this.initial = pinyin[0].charAt(0);
			this.number = hasNumber ? getPinYinT9Number(pinyin, limitnumber) : null;
		}

		@Override
		public int compareTo(Pinyin o) {
			String[] pinyin1 = pinyin;
			String[] pinyin2 = o.pinyin;
			if (pinyin1 == null || pinyin1.length == 0) {
				if ((pinyin2 != null && pinyin2.length != 0)) {
					return -1;
				}
				return 0;
			} else if ((pinyin2 == null || pinyin2.length == 0)) {
				return 1;
			}
			for (int i = 0; i < pinyin1.length && i < pinyin2.length; i++) {
				String p1 = pinyin1[i];
				String p2 = pinyin2[i];
				if (more) {
					int index1 = p1.indexOf(" ");
					if (index1 > 0) {
						p1 = p1.substring(0, index1);
					}
				}
				if (o.more) {
					int index2 = p2.indexOf(" ");
					if (index2 > 0) {
						p2 = p2.substring(0, index2);
					}
				}
				int result = p1.compareTo(p2);
				if (result != 0) {
					return result;
				}
			}
			if (pinyin1.length > pinyin2.length) {
				return 1;
			}
			if (pinyin2.length > pinyin1.length) {
				return -1;
			}
			if (more && !o.more) {
				return 1;
			}
			if (!more && o.more) {
				return -1;
			}
			return 0;
		}

	}

}
